### ISSUE TITLE
Tools without input files break workflows.list()

### ISSUE THREAD

**Issue by jmeppley** [galaxyproject/bioblend#108]
I have a workflow that includes a tool that has no input file. This tool creates a file from the input parameters only.

Line 212 in bioblend.galaxy.objects.wrapper.py:

```assert self.input_ids == set(self.inputs)```

Compares the declared inputs to the number of starting points in the DAG. Since this tool has no input files, it looks just like an input file in the DAG layout and gets put into the variable `self.input_ids`. But, it is NOT an input, so the above assertion fails.

I can solve the problem by removing the assertion, but I'm not sure what else that breaks.  The other option is to loop through the inputs and check them in the workflow data. The actual input files should have type set to 'data_input', while the tool should have type 'tool'.

**Comment by nsoranzo** [comment]
@jmeppley Thanks for the detailed bug report!

Can you test if it is fixed in my tree https://github.com/nsoranzo/bioblend ?

**Comment by jmeppley** [comment]
Looks good. Thanks.
