### ISSUE TITLE
Feature request: objects: Folder object attributes and methods

### ISSUE THREAD

**Issue by jmeppley** [galaxyproject/bioblend#114]
Once you have a Folder object from a Library, there is not much in the way of operations you can do.

Minimally, the parent attribute could point back to the Library or parent Folder.

Also, it'd be useful, but harder to implement, to be able to list, retrieve, and add datasets or sub-folders using the Folder object.

**Comment by nsoranzo** [comment]
Commit b408081dc5578bdc173708fc582c8a0ba777f50e adds the container attribute to Folder, which point back to the Library.

**Comment by jmeppley** [comment]
Thanks.

I was mucking about in my own fork. The folder data contains a "parent_id" key that seems to point to the parent folder (if the folder is not the library's root). I added a bit of code that would set the 'parent' attribute for Folders using that. I can set up a pull request if you'd be interested, but I don't have a full testing set up to properly check it out.

**Comment by nsoranzo** [comment]
> Also, it'd be useful, but harder to implement, to be able to list, retrieve, and add datasets or sub-folders using the Folder object.

All these actions should already be available through a `Library` object, I'm not sure reimplementing them inside the `Folder` class makes sense.

I'm closing this now, please open new issues for specific requests.
