### ISSUE TITLE
Add Endpoint for Tool Shed Repository Creation

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/bioblend#116]
https://github.com/galaxyproject/galaxy/pull/2#issuecomment-76266197

**Comment by erasche** [comment]
I'm working on doing this now...should it raise a ValueError if passed a value for `type` that's invalid (i.e. not in 'unrestricted', 'repository_suite_definition', 'tool_dependency_definition')

**Comment by erasche** [comment]
@martenson Additionally, should it be verified that categories contains at least ONE category?

While according to the API it's valid to have no categories...this isn't possible through the UI

**Comment by erasche** [comment]
In a fresh toolshed in Galaxy I see:
![image](https://cloud.githubusercontent.com/assets/458683/6442447/5d1cdd4c-c0b5-11e4-8cca-87aa9f6943e0.png)
however, as is evident via the repository, I can create them via the API.

**Comment by martenson** [comment]
@erasche I think in this case the UI is behind, I do not think you have to choose a category in the time of creation of a repo.

**Comment by erasche** [comment]
Okay, thanks for the quick response!
If you're saying that no category is officially required, I might suggest that the "View repositories by category" have an "Uncategorised" section of some sort.

**Comment by martenson** [comment]
@erasche yeah you can currently see it by browsing tools but repository that has no tool and no category is invisible. This seems logical to me. 'No Category' category...hmm, not sure.

**Comment by erasche** [comment]
I see your point that it being invisible in the "Repositories by category" view is logical, I just was worried that if this was going to be acceptable behaviour from the UI going forward, that the "default" view of the toolshed include those uncategorised tools, lest people forget to put categories and have their tools permanently invisible to people who want them. Then again, it'd be their fault...
