### ISSUE TITLE
Documentation inconsistencies

### ISSUE THREAD

**Issue by erasche** [galaxyproject/bioblend#118]
So! I was writing https://github.com/galaxy-iuc/parsec and realised that writing wrappers was dumb, so naturally I automated the process. For the command line parameter documentation, I discovered that Bioblend kept really great docs! Thanks y'all! However...there are some minor inconsistencies that I'll be making a PR on soon, but I have a few questions before the PR is completed:

- [`bioblend.galaxy.histories show_history()`](https://github.com/galaxyproject/bioblend/blob/master/bioblend/galaxy/histories/__init__.py#L52) are deleted/visible supposed to be booleans? Additionally, other values for `details` should be documented, or switched to a bool if all/none are the only options. Types is undocumented.
- [`bioblend.galaxy.histories create_history_tag()`](https://github.com/galaxyproject/bioblend/blob/master/bioblend/galaxy/histories/__init__.py#L215) does this really return a json object? Or should that be a dict
- `bioblend.galaxy.histories update_dataset/update_dataset_collection` both take kwds, probably should specify just what goes in there.
- [`bioblend.galaxy.libraries create_library()`](https://github.com/galaxyproject/bioblend/blob/master/bioblend/galaxy/libraries/__init__.py#L13) Does this really return a list? it's a create method...that really seems like it should return a single dict nota  list.
- [`bioblend.galaxy.libraries upload_file_from_server()`](https://github.com/galaxyproject/bioblend/blob/master/bioblend/galaxy/libraries/__init__.py#L224) here it's specified that if folder_id is empty, then the root folder will be used. Is this true everywhere? Should this be an optional param with None as a default? What does roles do?
- upload_file_from_server/upload_from_galaxy_filesystem are confusingly similar, but that's not bioblend's fault.
- [`bioblend.galaxy.libraries upload_file_from_server()`](https://github.com/galaxyproject/bioblend/blob/master/bioblend/galaxy/libraries/__init__.py#L257) what does roles do?

Minor complaint (and goodness knows I'm guilty of abusing `locals()` as well), but several places in the codebase switch between named args, and `**kwargs` automatically passed through. My automating wrapping of all the functions inspect method signatures (since I trust those more than the docs...)

**Comment by erasche** [comment]
- [`bioblend.galaxy.folders delete_folder()`](https://github.com/galaxyproject/bioblend/blob/master/bioblend/galaxy/folders/__init__.py#L27) that sort of thing looks like it could raise an exception. How do bioblend devs feel about adding exceptions to those sort of things that do validation before hitting the Galaxy server? Is that less desirable than letting Galaxy handle it?

**Comment by erasche** [comment]
There are a couple of examples where the documentation says:

 - Provide only one argument, `name` or `history_id` but not both.

It's troublesome for automatically wrapping that both of these are positional arguments and not keyword arguments, as they're both recognised as required when really they're both optional. (E.g. `bioblend.galaxy.histories.get_histories()`)

**Comment by erasche** [comment]
Strike my last-bug on my end.

**Comment by nsoranzo** [comment]
> ```bioblend.galaxy.libraries upload_file_from_server()``` here it's specified that if folder_id is empty, then the root folder will be used. Is this true everywhere? Should this be an optional param with None as a default? What does roles do?

It is true for all library upload_*/copy_from_dataset methods. It is already an optional param with None as default. I don't know that roles do.

> ```upload_file_from_server/upload_from_galaxy_filesystem``` are confusingly similar, but that's not bioblend's fault.

Indeed, the main difference is that for ```upload_file_from_server()``` files should be in ```library_import_dir```, while for ```upload_from_galaxy_filesystem()``` they may be everywhere in the server filesystem.

> ```bioblend.galaxy.folders delete_folder()``` that sort of thing looks like it could raise an exception when the ID doesn't start with 'F'. How do bioblend devs feel about adding exceptions to those sort of things that do validation before hitting the Galaxy server? Is that less desirable than letting Galaxy handle it?

No, in previous releases Galaxy was returning and accepting folder ids without the initial 'F', so if there is a specific bug we should fix it, otherwise let's leave it as it is.

**Comment by erasche** [comment]
@nsoranzo Thanks for the feedback, I appreciate it.

Good to know about all of those little idiosyncracies of the galaxy API.
