### ISSUE TITLE
Commit message not used

### ISSUE THREAD

**Issue by erasche** [galaxyproject/bioblend#122]
See [L250](https://github.com/galaxyproject/bioblend/blob/master/bioblend/toolshed/repositories/__init__.py#L250), mis-use of `dict()` vs `{}`, the commit message is stored in a key equal to its value, never being used.

I could've sworn I saw an email/IRC message about this recently, just discovered this while reading the code.

**Comment by jmchilton** [comment]
Will also fix galaxyproject/planemo#88.

**Comment by erasche** [comment]
@jmchilton ah, thanks, that was the issue I was remembering.
