### ISSUE TITLE
Unexpected error response

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/bioblend#126]
In some of the commits I've made to planemo (and the entirety of parsec), I've taken to attempting to parse the bioblend error code text as JSON because bioblend primarily passes the json response from Galaxy straight to the user.

However, in https://github.com/galaxyproject/bioblend/blob/master/bioblend/galaxyclient.py#L103 I encountered one of the few times when bioblend doesn't do that. Due to the prefixed text ("Unexpected...400: ") I cannot extract the nice `err_msg` key from the dict, and thus have to render the entire error message.

Would a PR be accepted to change this to just raise `r.text` instead of the formatted string? Submitted as an issue first in case there's commentary on changing error message strings.

**Comment by jmchilton** [comment]
So ideally all API exceptions would get handled through this method - they don't and that is a problem (https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/web/framework/decorators.py#L280). That said - we could build better exceptions on this side of things I think to handle the good and bad Galaxy exceptions:


    GalaxyExceptionGeneric()
        """Generic non-2XX response exception with r.text and status_code available"""
        ...

    GalaxyException(GalaxyExceptionGeneric):
        """properly formatted exception with extra fields for err_code, err_msg, extra_error_info, traceback (for admins)"""
        ...

**Comment by nsoranzo** [comment]
I'm not comfortable with just raising ```r.text```, but the GalaxyException approach would be nice!

**Comment by erasche** [comment]
@jmchilton the error message IS coming from the correct API decorator on the galaxy side. On the BioBlend side, it's being handled differently in some weird cases:

```python
bioblend.galaxy.client.ConnectionError: Unexpected response from galaxy: 400: {"traceback": "Traceback (most recent call last):\n  File \"/home/users/cpt/cpt/esr/Projects/galaxy/galaxy/lib/galaxy/web/framework/decorators.py\", line 251, in decorator\n    rval = func( self, trans, *args, **kwargs)\n  File \"/home/users/cpt/cpt/esr/Projects/galaxy/galaxy/lib/galaxy/webapps/tool_shed/api/repositories.py\", line 628, in create\n    raise exceptions.RequestParameterInvalidException( invalid_message )\nRequestParameterInvalidException: You already own a repository named <b>test<\/b>, please choose a different name.\n", "err_msg": "You already own a repository named <b>test<\/b>, please choose a different name.", "err_code": 400008}
```

Looking further, I'm getting `bioblend.galaxy.client.ConnectionErrors` for just about all of my exceptions. That said, I [used this sort of parsing in planemo](https://github.com/galaxyproject/planemo/blob/master/planemo/commands/cmd_shed_upload.py#L117) and that behaves nicely and prints `err_msg` rather than the JSON string.
.
