### ISSUE TITLE
set_library_permissions unexpected behaviour

### ISSUE THREAD

**Issue by Lobour** [galaxyproject/bioblend#137]
Hello,
When using set_library_permissions with a list containing all the user_ids of my galaxy instance for each of the roles, the last created user is not added to the said roles. I guess this is not working as intended.
Regards.

**Comment by nsoranzo** [comment]
Thanks for reporting this!
Additionally, a test for this method should be added.

Does it return with an error for you? Any message in the Galaxy server logs?

**Comment by Lobour** [comment]
Thank you for the quick answer!

This is the output i get in paster.log http://pastebin.com/XQ80X6dP .
This is the code I used : http://pastebin.com/fX3cQYYZ .

While retrying that today, it was actually three of the users that were not added to the data library permission roles. (The three last created users also.)

Oh, and I am using the last version of Galaxy.

Let me know if I can provide any more useful information.

**Comment by nsoranzo** [comment]
Hi @Lobour,
I've added a new `get_library_permissions()` method and a new test in commit c75a76c233d76bcb255e0738151b4b704118dfed: the test passes on Galaxy release_14.10 and later.

I tried to reproduce your problem with:

```python
import bioblend.galaxy
gi = bioblend.galaxy.GalaxyInstance(GALAXY_URL, GALAXY_API_KEY)
users_dict_list_new = gi.users.get_users(deleted=False)
user_id_list_new = [_['id'] for _ in users_dict_list_new]
gi.libraries.set_library_permissions('378af4a4ff4c15f4', access_in=user_id_list_new, modify_in=user_id_list_new, add_in=user_id_list_new, manage_in=user_id_list_new)
ret = gi.libraries.get_library_permissions('378af4a4ff4c15f4')
assert(set(_[1] for _ in ret['access_library_role_list']) == set(user_id_list_new))
assert(set(_[1] for _ in ret['modify_library_role_list']) == set(user_id_list_new))
assert(set(_[1] for _ in ret['add_library_item_role_list']) == set(user_id_list_new))
assert(set(_[1] for _ in ret['manage_library_role_list']) == set(user_id_list_new))
```

but it worked on a server with >500 users.

**Comment by nsoranzo** [comment]
After IRC chat, this was diagnosed as a Galaxy library UI problem, the user are correctly added.
