### ISSUE TITLE
set_library_permissions bug

### ISSUE THREAD

**Issue by Lobour** [galaxyproject/bioblend#141]
Hello, 

Sadly, apparently this is not only a UI bug.
I am trying to create a tool in order to allow normal users to create a data library with the right permissions for them on my Galaxy instance.

When using the set_library_permissions method, it sometimes works as intended, and sometimes gives the permissions to another user. I have no idea what is causing that.

Here is my script : http://pastebin.com/zHB89XgG 
(Of course, if I uncomment the asserts, I get assertion errors, also, I tried as well with the user id formatted as a list, and i get the exact same behaviour)

Here is the stdout : http://pastebin.com/eExmWVB3
There is not any stderr, and no errors showing in the paster.log .

I am using python 2.7.3, and the latest version of Galaxy.
Let me know if i can provide anything else...
Regards,
Loïc

**Comment by nsoranzo** [comment]
By looking at your stdout, it seems that the library permissions are correct, the user id is in fact the one specified, while the email is wrong. In this case, it would be a Galaxy bug.
Please, try to impersonate the user and see if you have the right access to the library.

Anyway `access_in`, `modify_in` and `add_in` must be lists.

**Comment by Lobour** [comment]
Oh, I just noticed that. Forget what i said about assertions then, I must have done something wrong.
(And I will use lists next times)

I impersonated the user, and I dont have access to the library with the one I should be able to.
For instance, with the code/stdout I provided, i would have access to the library with the user new6@new.com but not with new8@new.com.

**Comment by nsoranzo** [comment]
As explained on IRC, there was a documentation bug: `access_in`, `modify_in` and `add_in` must be lists of role ids, not of user ids.
