### ISSUE TITLE
No documentation for Roles on readthedocs

### ISSUE THREAD

**Issue by apetkau** [galaxyproject/bioblend#142]
This is related to issue #141 where there was an issue with the documentation for `set_library_permissions`.  However, there is currently no section on http://bioblend.readthedocs.org/en/latest/api_docs/galaxy/all.html#object-oriented-galaxy-api documenting the Roles.

**Comment by nsoranzo** [comment]
@afgane Is the documentation updated automatically?

**Comment by afgane** [comment]
Thus far, I've been doing it manually following a release. I updated it now and added a webhook so it will build the docs with each commit.

**Comment by nsoranzo** [comment]
Thanks, cool!

**Comment by apetkau** [comment]
Awesome, thanks for the quick response.  Note, I still don't see the Roles section on the readthedocs page.

**Comment by afgane** [comment]
Sorry about that - we did not keep up with listing what the modules to be included in the docs as they were added. Should be fixed now (in 1aea44760517eba382a7c6376fc3f98531351241).

**Comment by apetkau** [comment]
Awesome, thanks :).  I can see it all now.  Sorry for bugging you guys.  It was something that came up today for us.

**Comment by afgane** [comment]
No worries - thanks for noticing this.
