### ISSUE TITLE
Question about parameter in workflow

### ISSUE THREAD

**Issue by LongTianPy** [galaxyproject/bioblend#144]
Hi,

I'm writing a script for automating a workflow with bowtie2 in it. I have downloaded indices from bowtie2 website and wrote them in bowtie2_indices.loc. But how could I choose which reference index to use according to different sequences I will be using? I noticed that in run_workflow(), there is an argument 'param', but I'm not sure how to write this dictionary. 
Maybe like: 
param = {'bowtie2': {'source':'indexed', {'index':'hg19'}}}

**Comment by nsoranzo** [comment]
I think it should be:

```python
params = {
    'bowtie2': {
        'reference_genome': {
            'source': 'indexed',
            'index': 'hg19'
        }
    }
}
```

This will affect all steps having 'bowtie2' as tool id.
To modify only a specific bowtie2 step, you can just substitute 'bowtie' with the step id, which is also the recommended syntax.

**Comment by nsoranzo** [comment]
@LongTianPy: do my suggestions work for you? If yes, I'd like to improve the method documentation.

**Comment by LongTianPy** [comment]
@nsoranzo Hi, sorry I missed your previous reply. I have solved my problem in another approach but haven't tried your suggestions. My question about your suggestions is when I'm trying to figure out the parameter, should I go to the tool's XML wrapper to find out the keys of the dictionary?

**Comment by nsoranzo** [comment]
@LongTianPy: Looking at the XML is one option, the other is:

```python
w = gi.workflows.show_workflow('<workflow_id>')
step = [_ for _ in w['steps'].itervalues() if _['tool_id'] == '<tool_id>'][0]
print step['tool_inputs']
```

but this will give you the parameters only for the current selection of `<conditional>`s.

**Comment by LongTianPy** [comment]
@nsoranzo Thanks, this really helped me.

**Comment by nsoranzo** [comment]
Documentation has been improved in d3911bfe461353d7bb432689b1d8e6f67464a555, thanks for your question!
