### ISSUE TITLE
Tags cannot be added to a history

### ISSUE THREAD

**Issue by Airistotal** [galaxyproject/bioblend#145]
Galaxy commit bit: 32edb07930b17a868ed4088080b8d7fc577d1ce7

This is how I'm calling it:
_historyClient.create_history_tag(history.get('id'), "processed")
such that history is a history object and _historyClient is the GalaxyInstance.histories wrapper

It looks like it's dying on the server side, but I'm not sure.

Stack Trace and Error Message:
Traceback (most recent call last):
  File "get_stats.py", line 64, in <module>
    _historyClient.create_history_tag(history.get('id'), "processed")
  File "/usr/local/lib/python2.7/dist-packages/bioblend/galaxy/histories/__init__.py", line 314, in create_history_tag
    return Client._post(self, payload, url=url)
  File "/usr/local/lib/python2.7/dist-packages/bioblend/galaxy/client.py", line 171, in _post
    files_attached=files_attached)
  File "/usr/local/lib/python2.7/dist-packages/bioblend/galaxyclient.py", line 104, in make_post_request
    r.status_code, body=r.text)
bioblend.galaxy.client.ConnectionError: Unexpected response from galaxy: 500: {"traceback": "Traceback (most recent call last):\n  File \"/Warehouse/Users/dbouchard/galaxy/lib/galaxy/web/framework/decorators.py\", line 251, in decorator\n    rval = func( self, trans, *args, **kwargs)\n  File \"/Warehouse/Users/dbouchard/galaxy/lib/galaxy/webapps/galaxy/api/item_tags.py\", line 39, in create\n    tag = self._apply_item_tag( trans, self.tagged_item_class, kwd[ self.tagged_item_id ], tag_name, value )\n  File \"/Warehouse/Users/dbouchard/galaxy/lib/galaxy/web/base/controller.py\", line 2043, in _apply_item_tag\n    tag_assoc = self.get_tag_handler( trans ).apply_item_tag( trans, user, tagged_item, tag_name, tag_value )\nTypeError: apply_item_tag() takes at most 5 arguments (6 given)\n", "err_msg": "Uncaught exception in exposed API method:", "err_code": 0}

**Comment by jmchilton** [comment]
Thanks for the report @Airistotal - opened a Galaxy PR with a fix.

**Comment by nsoranzo** [comment]
As mentioned by @jmchilton this was a Galaxy bug, which is already fixed in `release_15.05`. I've added a specific test in commit 7e245216970d32317b5871465b3c6a6f0545ce64 . Thanks again for reporting!
