### ISSUE TITLE
Argument error in "install_repository_revision"

### ISSUE THREAD

**Issue by matthdsm** [galaxyproject/bioblend#152]
Hi

I am trying to install some tools in our local Galaxy instance through the BioBlend API. My code is as follows:

    #parse tool JSON
    try:
        with open(toolfile) as data_file:
            tools = json.load(data_file)
    except TypeError:
        sys.exit("Could not read toolfile")
    #install specified tools
    for tool in tools:
        print(tool["install_tool_dependencies"])
        gi.toolShed.install_repository_revision(
                tool_shed_url = tool["toolshed"], 
                name = tool["id"], 
                owner = tool["owner"],
                install_tool_dependencies = tool["install_tool_dependencies"], 
                install_repository_dependencies = tool["install_repository_dependencies"], 
                tool_panel_section_id = tool["tool_panel_section_id"], 
                new_tool_panel_section_label = tool["tool_panel_section_id"]
        )

the argument are parsed from a provided json file. As follows:

    [
    	{
    	"id":"data_manager_bowtie2_index_builder",
    	"owner":"devteam",
    	"install_tool_dependencies":true,
    	"install_repository_dependencies":true,
    	"tool_panel_section_id":null,
    	"toolshed":"https://toolshed.g2.bx.psu.edu/"
    }]

but when I run the code I get the following error: 

    Traceback (most recent call last):
      File "config_galaxy.py", line 60, in <module>
        _galaxyConfig(args.instance, args.api_key, args.tools)
      File "config_galaxy.py", line 41, in _galaxyConfig
        new_tool_panel_section_label = tool["tool_panel_section_id"]
    TypeError: install_repository_revision() takes at least 5 arguments (8 given)

Anybody any ideas why? Is there a mandatory argument short? I have not defined the revision code, because I just want the latest revision.

Thanks
Matthias

**Comment by nsoranzo** [comment]
It seems you are missing the `changeset_revision` required argument.

**Comment by bgruening** [comment]
@nsoranzo seems that Matthias wants to have the latest version and is omitting the revision. Imho, bioblend should be smart enough to get the latest revision in this case.

**Comment by nsoranzo** [comment]
Unfortunately this is a limitation of the Galaxy API: https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/webapps/galaxy/api/tool_shed_repositories.py#L206

**Comment by matthdsm** [comment]
Hi,
As Björn said, I'd like to have te latest version. Can I post a feature request somewhere to add this to the API? or someting like a 'latest' tag as changeset_revision?

**Comment by nsoranzo** [comment]
@matthdsm You can open an issue at https://github.com/galaxyproject/galaxy/issues/ .

**Comment by nsoranzo** [comment]
xref https://github.com/galaxyproject/galaxy/issues/549
