### ISSUE TITLE
Release version 0.6.1 

### ISSUE THREAD

**Issue by afgane** [galaxyproject/bioblend#154]
@jmchilton @nsoranzo 
I'd like to make the next minor release. You guys have something you'd like to get in or can I prepare it?

**Comment by jmchilton** [comment]
Have lots I would like to do - but I don't have time this week. Please push it out :).

**Comment by afgane** [comment]
Here's the CHANGELOG summary, in case there are things anyone would like to change: 32c07564ca6b36442b6455f66348292da7a780ea

**Comment by afgane** [comment]
Released.
