### ISSUE TITLE
unknown step type: u'data_collection_input', when running gi.workflows.list()

### ISSUE THREAD

**Issue by smithcr** [galaxyproject/bioblend#157]
Hi guys, 

I'm unable to list workflows via the object API - I get a ValueError. The data_collection_input isn't in the allowable set of step types.

the offending line:
https://github.com/galaxyproject/bioblend/blob/master/bioblend/galaxy/objects/wrappers.py#L274

Cheers,
Cam

**Comment by nsoranzo** [comment]
Hi Cameron,
unfortunately dataset collections are not well supported in BioBlend.objects yet, but I'd like to improve the situation! Can you test with https://github.com/nsoranzo/bioblend/commit/dc3dbecf41d023b8b16e1283dab578cd91438fad ?

**Comment by smithcr** [comment]
thanks! I will test this :)
