### ISSUE TITLE
Some ToolShedClient functions give a 404

### ISSUE THREAD

**Issue by yhoogstrate** [galaxyproject/bioblend#159]
Bioblend doesn't seem to behave as the manual (at page http://bioblend.readthedocs.org/en/latest/api_docs/galaxy/all.html?highlight=toolshedclient#bioblend.galaxy.toolshed.ToolShedClient) describes. When I run the following code:

```
from bioblend.galaxy import GalaxyInstance
import bioblend
bioblend.__version__
>>> '0.6.1'
from bioblend import toolshed
gi = GalaxyInstance(url='127.0.0.1', key='<key>')
tsc = bioblend.toolshed.repositories.ToolShedClient(gi)
tsc.repository_revisions()
```
It gives the following 404:

```
bioblend.galaxy.client.ConnectionError: GET: error 404: '<html>\r\n  <head><title>Not Found</title></head>\r\n  <body>\r\n    <h1>Not Found</h1>\r\n    <p>The resource could not be found.\r\n<br/>No route for /api/repository_revisions\r\n<!--  --></p>\r\n    <hr noshade>\r\n    <div align="right">WSGI Server</div>\r\n  </body>\r\n</html>\r\n', 0 attempts left: None
```

Could it be that the url has moved from:

```
gi.url + '/repository_revisions'
```

https://github.com/galaxyproject/bioblend/blob/master/bioblend/toolshed/repositories/__init__.py#L236
https://github.com/galaxyproject/bioblend/blob/master/bioblend/toolshed/repositories/__init__.py#L290

to:

```
gi.url + '/tool_shed_repositories'

```

--------

When I continue with the following code:

```
tsc.get_repositories()
```

It also gives a 404 error:

```
bioblend.galaxy.client.ConnectionError: GET: error 404: '<html>\r\n  <head><title>Not Found</title></head>\r\n  <body>\r\n    <h1>Not Found</h1>\r\n    <p>The resource could not be found.\r\n<br/>No route for /api/repositories\r\n<!--  --></p>\r\n    <hr noshade>\r\n    <div align="right">WSGI Server</div>\r\n  </body>\r\n</html>\r\n', 0 attempts left: None
```

Similarly, ```tsc.show_repository('65d5559f7c7e2cb9')``` results in a 404 to ```/api/repositories/65d5559f7c7e2cb9```. I think this url should be ```/api/tool_shed_repositories/65d5559f7c7e2cb9```.

To solve that, I guess the following needs to be changed (https://github.com/galaxyproject/bioblend/blob/master/bioblend/toolshed/repositories/__init__.py#L13):

```
self.module = 'repositories'
```

to

```
self.module = 'tool_shed_repositories'
```

p.s. The API key I use is linked to an admin account.

**Comment by nsoranzo** [comment]
@yhoogstrate Are trying to interact with a Galaxy instance to know the installed repositories or with a Tool Shed instance to know the available repositories?

**Comment by yhoogstrate** [comment]
@nsoranzo I see the problem now. I'm mixing up two different ToolShedClients. One that directly connects to a toolshed, and one that connects to a toolshed via galaxy.
