### ISSUE TITLE
Cannot select a dataset collection when using the objects.GalaxyInstance History client module

### ISSUE THREAD

**Issue by dgdekoning** [galaxyproject/bioblend#162]
Hello, I am trying to run a workflow that uses a data_collection_input as its first step and while I know the required dataset collection is present in the history I cannot seem to select it through BioBlend.

Looking into it I can verify the presence of the dataset collection and find the ID by using history.content_infos but I could not find any code that would let me select it in such a way that I can place it in an input map to run the workflow.

Am I missing something and is there a way to run the workflow through bioblend?

**Comment by dgdekoning** [comment]
Hello, I fixed my problem using functions from bioblend.galaxy.histories and bioblend.galaxy.dataset_collections while using 'TestGalaxyDatasetCollections.py' as an example and I thought I could add my solution into the bioblend.galaxy.objects code.

However, I ran into a problem where it looks like I would have to reimplement a lot of the methods to handle x number of datasets instead of only one. Is there a solution to this that would save me from having to do this?

**Comment by nsoranzo** [comment]
@dgdekoning The BioBlend.objects code need to be extended by adding DatasetCollection and HistoryDatasetCollectionAssociation classes plus support for those classes in workflows and histories. I think this may be a non trivial amount of work, so if you prefer I can ping you when there will be some code to test.

**Comment by dgdekoning** [comment]
@nsoranzo That would be great, thanks!

**Comment by amaclean199** [comment]
:+1:  for this

**Comment by dgdekoning** [comment]
Had to abandon it because of other pressing tasks, but I am keeping track of your pull request.
