### ISSUE TITLE
Documentation inconsistency on retry_delay

### ISSUE THREAD

**Issue by erasche** [galaxyproject/bioblend#165]
https://github.com/galaxyproject/bioblend/blob/c483c871b60821a11bf113bc9bc69a19efa0c355/bioblend/galaxy/client.py#L84 

disagrees with

https://github.com/galaxyproject/bioblend/blob/c483c871b60821a11bf113bc9bc69a19efa0c355/bioblend/galaxy/client.py#L50

Which should be correct?

**Comment by nsoranzo** [comment]
As usual, the code is correct and the docs are wrong ;)

Will fix in a min.

**Comment by erasche** [comment]
Okay, sounds good. Thanks @nsoranzo :)
