### ISSUE TITLE
Release version 0.7.0

### ISSUE THREAD

**Issue by afgane** [galaxyproject/bioblend#172]
I updated the CHANGELOG (see a7d42b9e34179e7501abfd0d877748f144fc3442) with the changes since the most recent release. @jmchilton @nsoranzo see if you have anything you'd like to add/update to be able to announce this release asap as per John's request.

**Comment by nsoranzo** [comment]
:+1:

**Comment by jmchilton** [comment]
Looks great @afgane, thanks a ton!

**Comment by afgane** [comment]
Published: https://pypi.python.org/pypi/bioblend/0.7.0

**Comment by jmchilton** [comment]
Thanks a ton for publishing that @afgane, beer debt :+1:.

**Comment by afgane** [comment]
No problem. Hope it all goes well.
