### ISSUE TITLE
can't download datasets

### ISSUE THREAD

**Issue by TorHou** [galaxyproject/bioblend#173]
I noticed an issue when I tried downloading small datasets from our server. I would get the error:
    
    Could not get display data for dataset: HistoryDatasetAssociation is not accessible by user

I tested this on our server in Freiburg.
Galaxy: release_15.10
bioblend: 0.7.0 (also tested 0.5.3, 0.6.1)

I'm not sure if it's a configuration issue, but I can circumvent this error when I change the way that the download_dataset builds the request and includes the api_key as argument.
If I change the download_dataset method in the file:

    galaxy/datasets/__init__.py

the way the request is built from:

    r = requests.get(url, verify=self.gi.verify)

to

    r = self.gi.make_get_request(url)

it works and I can download files.

**Comment by nsoranzo** [comment]
Cannot replicate on a fresh Galaxy release_15.10 clone:
```
import bioblend.galaxy
gi = bioblend.galaxy.GalaxyInstance('http://127.0.0.1:8080', '3941a6e6f4fd1463ea9df2abf42e3cfa')
gi.datasets.download_dataset('f2db41e1fa331b3e', file_path='.')
```

**Comment by TorHou** [comment]
Hmm. Thanks for testing, I'll talk to @bgruening about this some more.

**Comment by TorHou** [comment]
I tested locally as well and tried it on usegalaxy.org .. it all works, just not on galaxy.uni-freiburg.de. I'll test some more, but I guess we have to figure it out and this can be closed.
