### ISSUE TITLE
API does not work if Galaxy is not served at URL root

### ISSUE THREAD

**Issue by afgane** [galaxyproject/bioblend#178]
If Galaxy is available under a prefix (e.g., `<IP>/galaxy` (or similar)), the API's break as the prefix is not added in the URL structure.

```
from bioblend.galaxy import GalaxyInstance
gi = GalaxyInstance('115.146.87.64/galaxy', '93c0f511129b31c78d5f3793f7f8301e')
gi.histories.get_histories()  # breaks
```

**Comment by erasche** [comment]
Try adding a trailing slash.

**Comment by afgane** [comment]
You're right. Thanks. 
I added a note about that to the docs: 2e45e6a33354db54b1400e86b518ca8ec9199d7f
