### ISSUE TITLE
Unexpected response from galaxy: 500

### ISSUE THREAD

**Issue by zfrenchee** [galaxyproject/bioblend#186]
I'm able to perform get operations using this API, but post seems to fail. Any ideas as to why? 

```
  File "run_pipeline.py", line 45, in main
    uploadedFile = toolClient.upload_file(input_path, history['id'])
  File "/usr/local/lib/python2.7/site-packages/bioblend/galaxy/tools/__init__.py", line 148, in upload_file
    return self._tool_post(payload, files_attached=True)
  File "/usr/local/lib/python2.7/site-packages/bioblend/galaxy/tools/__init__.py", line 218, in _tool_post
    return Client._post(self, payload, files_attached=files_attached)
  File "/usr/local/lib/python2.7/site-packages/bioblend/galaxy/client.py", line 171, in _post
    files_attached=files_attached)
  File "/usr/local/lib/python2.7/site-packages/bioblend/galaxyclient.py", line 131, in make_post_request
    r.status_code, body=r.text)
bioblend.galaxy.client.ConnectionError: Unexpected response from galaxy: 500: 

<html>
<head><title>500 Internal Server Error</title></head>
<body bgcolor="white">
<center><h1>500 Internal Server Error</h1></center>
<hr><center>nginx/1.4.6 (Ubuntu)</center>
</body>
</html>
```

**Comment by zfrenchee** [comment]
It seems like this might be due to file size. How large is the maximum upload allowed to be? I managed to get a tiny text file uploaded, but couldn't this error was generated when I tried to upload my 400MB bam file. Should 400 MB be allowed?

**Comment by martenson** [comment]
Large files should generally be uploaded via FTP. That said 400MB should not be an issue. Which Galaxy are you connecting to?

**Comment by zfrenchee** [comment]
I'm running my own galaxy courtesy of @bgruening's https://github.com/bgruening/docker-galaxy-stable.

**Comment by martenson** [comment]
@zfrenchee can you check the Galaxy's log?

**Comment by zfrenchee** [comment]
Where can I find the log? (sorry!)

**Comment by martenson** [comment]
You probably need to look inside of the image that runs it, so this depends on how you run docker.

this should help you: https://github.com/bgruening/docker-galaxy-stable#advanced-logging

**Comment by zfrenchee** [comment]
I couldn't find any evidence of the failed uploads in the logs, just tools being initialized after the successful uploads (of very small files).

**Comment by bgruening** [comment]
This was fixed offline with @zfrenchee. It was a `no free disc space error`.

**Comment by martenson** [comment]
thanks @bgruening
