### ISSUE TITLE
LibraryClient.upload_file_from_server() documentation

### ISSUE THREAD

**Issue by zfrenchee** [galaxyproject/bioblend#187]
The method says it's used to
```
Upload all files in the specified subdirectory of the Galaxy library import directory to a library.
```
which relies on this parameter `library_import_dir` in `galaxy.ini`. In `galaxy.ini` it's annotated with
```
# Add an option to the library upload form which allows administrators to upload a directory of files.
```
and on the [wiki](https://wiki.galaxyproject.org/Admin/DataLibraries/UploadingLibraryFiles) it's annotated with:
```
# Directories of files contained in the following directory can be uploaded to a library from the Admin view
```

But I still don't understand what this parameter is, and how it might solve my problem of trying to upload files from my sftp server to my galaxy server by running code which uses this API.

**Comment by martenson** [comment]
> trying to upload files from my sftp server to my galaxy server

@zfrenchee  What do you mean by this? Are you trying to import data from your FTP server's folder to Galaxy that is on the same machine/network or am I misunderstanding? 

If so the method you ask about is a correct choice afaik. You need to set `library_import_dir` in the galaxy.ini to `/path/of/your/folder` and then you will be able to import subfolders from it (given that you are admin) by specifying `server_dir` parameter in the call of `upload_file_from_server()` method.

**Comment by zfrenchee** [comment]
Hi @martenson, 
No, the galaxy instance and the files I want to import are on different servers. The files are on a local server, which I can access via sftp, the galaxy instance is on a cloud provider.

**Comment by martenson** [comment]
@zfrenchee Libraries can not act as an FTP client I think. Your best bet is probably to transfer the files to the Galaxy machine using sftp or sth similar.

**Comment by zfrenchee** [comment]
Okay, that helps clarify things. Then I suppose my last question is, if we want to run this in production, what is the most effective way to transfer large quantities of data to galaxy? (and then I'll close the issue)

**Comment by martenson** [comment]
I would recommend running an ftp server on the same file system as Galaxy
if users have the data.

If you control all the data then just transfer it to the Galaxy file system
in one batch.

After either of these you can easily import it.
