### ISSUE TITLE
New release (with 16.07?)

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/bioblend#193]
It would be cool if we could get a new bioblend release soon.
With #190 and https://github.com/galaxyproject/galaxy/pull/2554 we can support installing conda dependencies in the ansible-galaxy-tools role.

Ping @afgane

**Comment by afgane** [comment]
Is there anything else to wait for or can the release be drafted?

btw, @nsoranzo now also has pypi access so the release does not need to wait on me in the future.

**Comment by mvdbeek** [comment]
Cool, thanks @afgane. Not as far as I know, to me the sooner the better.

**Comment by afgane** [comment]
@nsoranzo Could you take a look at the CHANGELOG to see if I missed things you think should be highlighted?

**Comment by nsoranzo** [comment]
@afgane I've committed a couple of tweaks, thanks for the work on it!

**Comment by afgane** [comment]
0.8.0 released: https://github.com/galaxyproject/bioblend/releases/tag/v0.8.0
