### ISSUE TITLE
Inconsistent parameter names

### ISSUE THREAD

**Issue by afgane** [galaxyproject/bioblend#194]
I just noticed that a number of methods use `toolShed_id` as a parameter (it looks like it's all the methods named `show_repository`; e.g., https://github.com/galaxyproject/bioblend/blob/master/bioblend/galaxy/toolshed/__init__.py#L38), which is (1) inconsistent with the rest of the code; and (2) not PEP8 compliant. Should this be deprecated in favor of `tool_shed_id` or we just forget it?

**Comment by nsoranzo** [comment]
I don't like `toolShed_id` either, but I guess it is part of our API at this point unfortunately.
