### ISSUE TITLE
Using BioBlend for updating tools in a local instance?

### ISSUE THREAD

**Issue by pajanne** [galaxyproject/bioblend#195]
I would like to know if it is possible to do a batch update of all installed tools using BioBlend in a local Galaxy instance. I am not finding it in the doc either as an issue here. Would you be able to help me? Thanks.

**Comment by afgane** [comment]
Not natively. Take a look at this script though https://github.com/galaxyproject/ansible-galaxy-tools/blob/master/files/install_tool_shed_tools.py that can be made do what you're asking about. To use it, you'd need to create a list of tools on your instance (you can use this script for that https://github.com/galaxyproject/ephemeris/blob/master/ephemeris/get_tool_list_from_galaxy.py) and then just remove the revision that's auto-included in that file. The initial script will then install the latest revision of the listed tools.
