### ISSUE TITLE
AttributeError while instantiating WorkflowClient

### ISSUE THREAD

**Issue by jibe-b** [galaxyproject/bioblend#203]
I try to instantiate a [bioblend.galaxy.workflows.WorkflowClient](https://bioblend.readthedocs.io/en/latest/api_docs/galaxy/all.html#bioblend.galaxy.workflows.WorkflowClient)

First step is to instantiate a Galaxy instance

>gi = GalaxyInstance(galaxy_url, api_key)

Then a WorkflowClient:

>wo = WorkflowClient(gi)
>**AttributeError: 'GalaxyInstance' object has no attribute 'url'**

I tried to solve this issue by adding the attribute to the object:

>gi.url = galaxy_url
>wo = WorkflowClient(gi)

But when calling a method such as:

> wo.import_workflow_from_local_path('/path/to/file')

> **AttributeError: 'GalaxyInstance' object has no attribute '_make_url'**

The problem may be due to the GalaxyInstance that is passed as parameter of WorkflowClient.

**Comment by nsoranzo** [comment]
Hi @jibe-b,
I think you used the wrong import for GalaxyInstance. Did you use:
```
from bioblend.galaxy.objects import GalaxyInstance
```
? If yes, then you are mixing the procedural and Object-Oriented API. If you want to use the procedural API you need to use this import:
```
from bioblend.galaxy import GalaxyInstance
```
Once you have created your `gi`, you don't need to create the `WorkflowClient` object, it's already available as:
```
gi.workflows
```

If I have made the wrong guess and this is not the problem, please include the full code needed for reproduce the error (e.g. the imports you've used) and the complete traceback, thanks!

**Comment by nsoranzo** [comment]
Thanks @jibe-b for the follow-up!
