### ISSUE TITLE
Move bioblend tests into the bioblend module.

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/bioblend#208]
If one does a pip install bioblend - the tests get installed into a tests package currently - which seems to be bad practice. They should be excluded when doing ``find_packages`` or better yet - moved and installed within the bioblend namespace.

@nsoranzo Any objections to me making the tests more usable as part of the install this way?

**Comment by nsoranzo** [comment]
@jmchilton Thanks for reporting! I'd probably prefer to exclude them. @afgane ?

**Comment by jmchilton** [comment]
But they are so useful :cry: - we need to work toward automated tests of Galaxy configurations and deployments and formalizing a bioblend-based test suite would be big step toward that. Also more use of that testing framework would probably result in more tests - as people find regressions, etc... they want to ensure do not happen.

**Comment by nsoranzo** [comment]
I see your point, I just don't want them to be somehow considered part of the API. What's the problem with launching BioBlend tests with `./run_bioblend_tests.sh` for your use cases?

**Comment by jmchilton** [comment]
I'll open a PR to be specific in answering this.

**Comment by guerler** [comment]
I have issues running tests locally. I cloned a clean bioblend and galaxy repo and then called ./run_bioblend_tests.sh, the initial run somtimes works but if I run it again the test environment fails to setup properly. It complains about duplicate test users.

**Comment by nsoranzo** [comment]
@guerler `./run_bioblend_tests.sh` always initialises a new SQLite database in a temporary directory, maybe the previous Galaxy instance is still around and using the port? You can also check the `main.log` inside the Galaxy repo dir.

**Comment by guerler** [comment]
Its not the other Galaxy instance, when running `./run_bioblend_tests.sh` the first time it seems to process it but I cannot find details on which individual unit tests failed (is there a log file?). Instead the screen displays a long list of parsing warnings regarding missing spaces (is there a way to disable these?). When running it again, I see a warning claiming that the user already exists.

**Comment by nsoranzo** [comment]
If the warnings are about stuff in `.eggs`, try to update BioBlend from GitHub, I have already fixed this in commit 3ec45d381616b29edb8e421bb94f52f6893d0c0e . Can you gist the full output of `./run_bioblend_tests.sh` ? Also, is under Linux or Mac?

**Comment by guerler** [comment]
I am running it on Mac, and its the latest BioBlend repo. Here is a link to one of the outputs:
https://gist.github.com/guerler/f76e7fc9ffcd46a21bab03d4ea5cc7b4

**Comment by nsoranzo** [comment]
You should move the `galaxy` directory outside of the bioblend tree, otherwise it will be tested with flake8!

Moreover, the `./run_bioblend_tests.sh` script was never tested on Mac and indeed broken there. I've tried to fix it with https://github.com/nsoranzo/bioblend/commit/ce146075c6897b311a9ca3c107cf872e40c45551 (not pushed to https://github.com/galaxyproject/bioblend yet). If you can apply it and re-test, that would be super-useful.

**Comment by guerler** [comment]
Looks like this now: https://gist.github.com/guerler/3a700566c3775485a1bab8ef1d29f2da

**Comment by nsoranzo** [comment]
There seems to still be a `bin/` and `lib/` directories which are not part of bioblend (maybe residues of a virtualenv), which you can probably remove (`git status` should tell you if there are more).

There was still a small bug on the OSX fix above, I've pushed the corrected fix to https://github.com/galaxyproject/bioblend now.

**Comment by guerler** [comment]
Looks like progress: https://gist.github.com/guerler/f52ac816bcb9f1eff8c785512822fc88

**Comment by guerler** [comment]
I added the API key and re-run it. Now, I get this error here, it does not seem to pick up the API key I provided. https://gist.github.com/guerler/4f7eaffeaaf8907c89f9ffcb2c2210da

**Comment by nsoranzo** [comment]
I had fixed only one of the two occurrences of the `tr: Illegal byte sequence` problem, should be OK now with commit 4fc9d2920855ee1777dee0ac20553f0e3e8b8451, sorry for the trouble.

**Comment by guerler** [comment]
No worries. Thanks for fixing these issues. It seems to work. Awesome.

**Comment by nsoranzo** [comment]
Thank you for reporting the issue!

**Comment by nsoranzo** [comment]
@jmchilton I think that's resolved by #209, if not please reopen.
