### ISSUE TITLE
API key being send in URL query

### ISSUE THREAD

**Issue by jvolkening** [galaxyproject/bioblend#211]
I've been testing out the Galaxy API via bioblend in order to pull data into Galaxy automatically from a mass spectrometer. I noticed in testing on a temporary Galaxy instance that requests are sending my API key as part of the URL query string. This is a pretty big (!!!) security vulnerability for a production server. Is there a way to put the key within the encrypted payload, such as in the HTTP headers (see for example the Basespace API)?

**Comment by dannon** [comment]
I'd strongly recommend using https to secure a production serve.  My thinking on this is that anyone sniffing packets would be able to read the headers as well, so I'd rather it be obvious that the query is not secure.

**Comment by jvolkening** [comment]
The production server uses https. That's the point - headers are encrypted over HTTPS but URLs are available for all to see regardless of whether TLS/SSL is in use. In my testing, the API key was being sent as part of the URL, which TLS/SSL encryption does nothing to change. I was hoping there was a setting I was missing that would put the key in the headers, which would be properly encrypted over HTTPS.

**Comment by dannon** [comment]
Hrmm.  I thought the query string was also encrypted over HTTPS.  Let me verify this.

**Comment by jvolkening** [comment]
I was just about to post that I think you are right - my understanding was faulty. There are still downsides to putting sensitive data in the query string (such as being stored in server logs, etc) but it's not readily visible as I had thought.

**Comment by martenson** [comment]
Server side logs are considered protected I believe and the only other place where the url is stored exposed is the browsers history. We cannot do much about that though.

**Comment by nsoranzo** [comment]
@martenson You are not supposed to use BioBlend through a browser, but I get you were thinking in general about Galaxy API.

@jvolkening Should we close the issue then?

**Comment by jvolkening** [comment]
@martenson Well, the REST API could be configured to read credentials from HTTP headers, which would not be stored in browser. This was my understanding of the "best practices" way to do it. But the bioblend calls would not be from a browser so that doesn't worry me.

In any case, my initial concerns were overblown. Sorry for the noise.

**Comment by dannon** [comment]
Yeah, just to follow up on this, I verified with a local test here, and the query string *is* encrypted.

I don't think it would be particularly difficult to implement header-based api key auth if someone wanted to take it on, and I could point you in the right direction if you wanted to do it, but we should open an issue on galaxyproject/galaxy for that if it's deemed important.

**Comment by jvolkening** [comment]
> Server side logs are considered protected I believe

Just to clarify - is there an assumption here that the admin has modified the default umask or otherwise changed permissions on files owned by the user Galaxy is running  under? Typically Galaxy is run as a regular user, and in many distros the default umask is 022 which makes user files world-readable. Thus, the log file containing the API keys would (with default permissions) be exposed to any users on the local system.

Would it make sense for Galaxy to check and enforce specific file permissions on potentially senstive files, as some software does? Is it worth opening an issue on the Galaxy repo about this or am I still overthinking it?

Adding the option to put the API key in the HTTPS header turned out to be a matter of a single line edit -- I'm preparing a PR for the Galaxy repo right now for others to look over.

**Comment by martenson** [comment]
@jvolkening My assumption is more primitive than that - I expect admin of the system to keep the configs, logs, database, and datasets secure. 

> Is it worth opening an issue on the Galaxy repo about this or am I still overthinking it?

Worth, I believe.
