### ISSUE TITLE
Publishing a history with update_history bug?

### ISSUE THREAD

**Issue by dwightkuo** [galaxyproject/bioblend#214]
I'm trying to use bioblend (v0.7.0) to publish histories but it doesn't seem to be working
`

    gi = galaxy.GalaxyInstance(args.url, args.key)

    history = gi.histories.create_history(name = 'testing')

    result = gi.histories.update_history(history['id'], {'published' :  True})

    print(result)

    result = gi.histories.update_history(history['id'], published=True)

    print(result)
`
I get error code 400 when I try either method above.

**Comment by nsoranzo** [comment]
@dwightkuo Thanks for reporting the issue, it should be fixed in commit b8a9ce6cda06c04ce5bb0a3b138389372fa5a59f , available in the `master` branch.
