### ISSUE TITLE
adding/deleting a quota

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/bioblend#218]
It would be nice to have the possibility to add/edit quotas via bioblend. I have seen that the API supports this. 

Actually I could imagine to try implementing this on my own, but the API documentation on this subject is quite sparse (parameters are undocumented). Maybe I'm able to dig in the API sources to get the infos on necessary parameters. But I guess I could need some input from experienced developers.

**Comment by pcm32** [comment]
I would be really interested as well in being able to set user/group quotas through bioblend. Have you had any chance to make it work @bernt-matthias?

Thanks!
Pablo

**Comment by bernt-matthias** [comment]
Unfortunatelly .. no.

**Comment by nsoranzo** [comment]
xref. #226

**Comment by bernt-matthias** [comment]
I guess we can close this issue.

**Comment by nsoranzo** [comment]
Fixed by #226.
