### ISSUE TITLE
 bioblend.galaxy.datasets.DatasetClient.show_stdout broken for private histories/datasets

### ISSUE THREAD

**Issue by edwardsnj** [galaxyproject/bioblend#221]
Perhaps this represents a gap in the Galaxy API (since the show_stdout method appears to work around it), but the current strategy (see below) doesn't populate the galaxysession authentication Cookie before accessing the galaxy (non-API) url using urlopen. 

I get a HTML formatted page back (which includes text to indicate I should login).

Similarly for bioblend.galaxy.datasets.DatasetClient.show_stderr.

```
    def show_stdout(self, dataset_id):
        """
        Get the stdout output of a dataset.

        :type dataset_id: str
        :param dataset_id: Encoded dataset ID
        """
        res = urlopen(self.url[:-len("/api/datasets/") + 1] + "/datasets/" + dataset_id + "/stdout")
        return res.read()

```

**Comment by nsoranzo** [comment]
@edwardsnj I think the proper way to access stdout and stderr is through the job API using `full_details=True`, see https://bioblend.readthedocs.io/en/latest/api_docs/galaxy/all.html#bioblend.galaxy.jobs.JobsClient.show_job . Feel free to reopen if this does not work for you.

**Comment by edwardsnj** [comment]
Ah. Good lead on getting to the right answer - in fact it is simpler than jobs.show_job - bioblend.galaxy.histories.HistoryClient.show_dataset_provenance returns a dictionary with stdout and stderr keys (populated too! :-) I found this because I needed a way to associate jobs with histories to try out your suggestion.

Thanks!
