### ISSUE TITLE
show_stderr / show_stdout do not work with REMOTE_USER

### ISSUE THREAD

**Issue by erasche** [galaxyproject/bioblend#222]
ping @dannon as well. This is more of an "FYI I hit this but it is not actively impacting me."

http://bioblend.readthedocs.io/en/latest/_modules/bioblend/galaxy/datasets.html#DatasetClient.show_stderr

both those unfortunately call non-API routes. It would be optimal if the API could support this so I don't have to add another exception to my proxy rules.

**Comment by nsoranzo** [comment]
@erasche Is this a duplicate of https://github.com/galaxyproject/bioblend/issues/221 ?

**Comment by erasche** [comment]
I really need to start checking for duplicates first... yes it is, my apologies.

**Comment by nsoranzo** [comment]
No worries, it's funny that the 2 issues were reported in a 6 hours span, despite this problem being there since these methods were introduced more than 2 years ago!
