### ISSUE TITLE
New 0.9.0 release

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/bioblend#224]
Requested by @erasche in https://github.com/galaxy-iuc/parsec/pull/10 . Also needed to officially support the forthcoming Galaxy ``release_17.05``.

@afgane I've updated `CHANGELOG.md`, if you want to take a look. Anything outstanding from your side (apart from open pull requests)?
I can do the release this time, if you like. What's the process exactly? I've come up with the following:
```bash
# Cleanup
find . -name '*.pyc' -delete
rm -rf dist/
# Install latest versions of pip, setuptools and twine in a virtualenv
. .venv/bin/activate
pip install --upgrade pip setuptools
pip install --upgrade twine
# Create 
python setup.py sdist
python setup.py bdist_wheel
twine upload dist/*
```

**Comment by bgruening** [comment]
@nsoranzo it can be that @afgane is on vacation for a few weeks.

**Comment by nsoranzo** [comment]
Ping @afgane

**Comment by afgane** [comment]
Sorry for the delay - missed this while I was away.

Looks good, and feel free to do a release @nsoranzo. As far as the process goes, what you outlined looks like it will work. I use Python 3.6 and hence don't use twine so instead just do `python setup.py dist upload` (requires `~/.pypirc`)...

The only thing that's missing in your list is setting the version in `bioblend/__init__.py` before the release.

**Comment by erasche** [comment]
@afgane, twine is available for python 3. Most of us use it due to [the security implications](https://pypi.python.org/pypi/twine) of using `dist upload` in the past.

**Comment by afgane** [comment]
My understanding was that the security issues were resolved for Py3.2+?

**Comment by erasche** [comment]
I read that as "only recently" = "there was a time when py3.2+ were vulnerable", not "only recently [it was resolved] which covers releases up to py3.2, after which they were secure by default"

**Comment by nsoranzo** [comment]
@afgane What about `docs/_build/` ? Should I clean it up or run `make -C doc/ html` before creating the package and wheel?

**Comment by afgane** [comment]
I don't recall explicitly doing anything about `docs/_build` before a release. I'd only build them locally to check if they build properly but we quit including built content in the repo years ago.

Regardless, looks you figured it out and the release looks good! Thanks.

**Comment by nsoranzo** [comment]
Now also available on PyPI as both source and wheel distributions.

**Comment by bgruening** [comment]
@nsoranzo thanks a lot for the release!

**Comment by nsoranzo** [comment]
Hopefully the release process will be much faster with https://github.com/galaxyproject/bioblend/commit/04ef8e849a15c679aee7b791c3a84e24ea616ce6 .
