### ISSUE TITLE
export_workflow_dict is not available?

### ISSUE THREAD

**Issue by rat-codes** [galaxyproject/bioblend#229]
Hi,

I am getting the following error when using 
```
wfc.export_workflow_dict('ee3742ed6d8b4a0c')
AttributeError: 'WorkflowClient' object has no attribute 'export_workflow_dict'
```

But, _export_workflow_json_ returns the expected info.

Thanks,
Aarthi

**Comment by nsoranzo** [comment]
This is going to be available in the soon-to-be-released BioBlend 0.9.0 (or if you install from GitHub).
