### ISSUE TITLE
Error with upload functions (both ToolClient and LibraryClient)

### ISSUE THREAD

**Issue by aarthi-mohan** [galaxyproject/bioblend#232]
Hi,

I am trying to execute a bioblend script from within Java using Jython. While bioblend script works from command-line with any file size, the same fails when called from within Java with the following errors. I have tried it with 1kb and 400mb fastq files

```
Properties p = new Properties();
p.setProperty("python.path","C:\\Python27\\Lib\\site-packages");
PythonInterpreter.initialize(System.getProperties(), p , new String[]{""});
PythonInterpreter interp = new PythonInterpreter();
interp.exec("history = historyClient.create_history(history_name)");
interp.exec("hid = history['id']");
interp.set("fname", new PyString("C:\\Users\\EPHAART\\Documents\\Project\\galaxy_demo_data\\a_1.fastq"));
interp.exec("toolClient.upload_file(fname, hid)");
```
> Exception in thread "MainThread" Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "C:\Python27\Lib\site-packages\bioblend\galaxy\tools\__init__.py", line 149, in upload_file
>     return self._tool_post(payload, files_attached=True)
>   File "C:\Python27\Lib\site-packages\bioblend\galaxy\tools\__init__.py", line 219, in _tool_post
>     return Client._post(self, payload, files_attached=files_attached)
>   File "C:\Python27\Lib\site-packages\bioblend\galaxy\client.py", line 156, in _post
>     return self.gi.make_post_request(url, payload=payload,
>   File "C:\Python27\Lib\site-packages\bioblend\galaxyclient.py", line 115, in make_post_request
>     payload = MultipartEncoder(fields=payload)
>   File "C:\Python27\Lib\site-packages\requests_toolbelt\multipart\encoder.py", line 119, in __init__
>     self._prepare_parts()
>   File "C:\Python27\Lib\site-packages\requests_toolbelt\multipart\encoder.py", line 240, in _prepare_parts
>     self.parts = [Part.from_field(f, enc) for f in self._iter_fields()]
>   File "C:\Python27\Lib\site-packages\requests_toolbelt\multipart\encoder.py", line 489, in from_field
>     return cls(headers, body)
>   File "C:\Python27\Lib\site-packages\requests_toolbelt\multipart\encoder.py", line 482, in __init__
>     self.len = len(self.headers) + total_len(self.body)
> TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

```
interp.exec("library = libraryClient.create_library('new_lib')");
interp.exec("print 'lib id ' , library['id'] ");
System.out.println("uploading files to library");
interp.exec("libraryClient.upload_file_from_local_path(library['id'], fname)");
```
> Exception in thread "MainThread" Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "C:\Python27\Lib\site-packages\bioblend\galaxy\libraries\__init__.py", line 357, in upload_file_from_local_path
>     return self._do_upload(library_id, file_local_path=file_local_path,
>   File "C:\Python27\Lib\site-packages\bioblend\galaxy\libraries\__init__.py", line 281, in _do_upload
>     return Client._post(self, payload, id=library_id, contents=True,
>   File "C:\Python27\Lib\site-packages\bioblend\galaxy\client.py", line 156, in _post
>     return self.gi.make_post_request(url, payload=payload,
>   File "C:\Python27\Lib\site-packages\bioblend\galaxyclient.py", line 115, in make_post_request
>     payload = MultipartEncoder(fields=payload)
>   File "C:\Python27\Lib\site-packages\requests_toolbelt\multipart\encoder.py", line 119, in __init__
>     self._prepare_parts()
>   File "C:\Python27\Lib\site-packages\requests_toolbelt\multipart\encoder.py", line 240, in _prepare_parts
>     self.parts = [Part.from_field(f, enc) for f in self._iter_fields()]
>   File "C:\Python27\Lib\site-packages\requests_toolbelt\multipart\encoder.py", line 489, in from_field
>     return cls(headers, body)
>   File "C:\Python27\Lib\site-packages\requests_toolbelt\multipart\encoder.py", line 482, in __init__
>     self.len = len(self.headers) + total_len(self.body)
> TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

I saw a similar issue asked previously, and checked that my disc space is not full :(
Appreciate any hints!

Thanks,
Aarthi

**Comment by nsoranzo** [comment]
Not sure how to help here, maybe @jmchilton can advise?
