### ISSUE TITLE
No input dataset error in invoke_workflow()

### ISSUE THREAD

**Issue by jhl667** [galaxyproject/bioblend#235]
Hi there,

I am using v0.8.1.  Up until now, I have continued to use the deprecated run_workflow() function, and it has worked fairly well.  As my workflows become more complex (>100 steps), I have run in to a problem where identical workflows are written to a given history several times, followed by bioblend throwing a ConnectionError.  I generally am trying to start 20-40 workflows in the same process, so many of them will be correctly initiated before the error occurs.  Smaller workflows (~50 steps) seems to be fine.

EDIT: Solved first problem by giving VM additional resources (load average was skyrocketing).

So, my thought was to stop using the deprecated run_workflow() in favor of invoke_workflow().  A statement in the documentation made me think this might help my particular situation.  The problem I run in to now is that invoke_workflow() complains that it can't find an expected input step.  Since this works fine with run_workflow, seems strange.  I can see exactly which input dataset is causing problems, but I can't figure out why the problems are occurring.

> bioblend.ConnectionError: Unexpected HTTP status code: 400: {"err_msg": "Workflow cannot be run because an expected input step '43580' has no input dataset.", "err_code": 0}

Every time I've seen this in the past, it was a very easy fix, and generally has something to do with the workflow not being strung together correctly.  Unfortunately, doesn't seem to be the case this time.  Any thoughts?

**Comment by rat-codes** [comment]
Not sure, if this is what is causing problem for you too. Please see the below from documentation,
[http://bioblend.readthedocs.io/en/latest/api_docs/galaxy/all.html#module-bioblend.galaxy.workflows](url)

> Historically, the run_workflow method consumed a dataset_map data structure that was indexed by unencoded workflow step IDs. These IDs would not be stable across Galaxy instances. The new inputs property is instead indexed by either the order_index property (which is stable across workflow imports) or the step UUID which is also stable.

In my case, I do not see this error anymore once I moved from "_step_id_" to "_step_index_" (**"0"** in the below code) when using _invoke_workflow_ call. You can get the _step_index_ for inputs by downloading the workflow.ga file from UI (should also be available from the _export_workflow_dict_ function)
`data_wstep_index = {"0": {"id": dataset_collection["id"], "src": "hdca"}}`

Aarthi

**Comment by jhl667** [comment]
Thanks for the suggestion @rat-codes.  I ended up reformulating the workflow anyways, and the problem went away.  It never was completely clear to me what the issue was.

**Comment by jhl667** [comment]
@rat-codes Had to come back to this issue after we went live on a large 150+ dataset workflow, of which 30 would be run at a time.  Again, was seeing the first maybe 25 runs do fine, but then would see this behavior where the same workflow would be invoked several times in the same history.  Anyways, invoke_workflow is crucial for this, as the docs mention, but also your suggestion of utilizing the step_index solved for the 'no input dataset' error.

**Comment by nsoranzo** [comment]
>  Again, was seeing the first maybe 25 runs do fine, but then would see this behavior where the same workflow would be invoked several times in the same history.

That looks like a Galaxy bug. Did the job/workflow handler process die (e.g. out of memory) while scheduling the workflow?

**Comment by jhl667** [comment]
@nsoranzo Yes, it did.  Increasing available memory solved the problem temporarily, until the workflows increased on number and complexity.  I am seeing this with an old version of Galaxy (14.10 I believe) so not sure whether this is even still a problem.  Also, as I said, it does seem that using invoke_workflow stopped the issue.
