### ISSUE TITLE
Issue when running nosetests

### ISSUE THREAD

**Issue by drosofff** [galaxyproject/bioblend#236]
Hi there,
I suppose that a bunch of contributors are on their route to the GCC2017. I am looking to seeing you (Tuesday for me).

Well I am trying to refresh the Travis testing of GalaxyKickStart and currently I am running in trouble, basically when
`py27 runtests: commands[0] | /home/galaxy/bioblend-master/.tox/py27/bin/python setup.py nosetests -e test_download_dataset` is invoked.

In brief, the test is fetching https://github.com/galaxyproject/bioblend/archive/master.zip
and I can see that after `/home/galaxy/bioblend-master/setup.py` install, things turn latter bad with
https://travis-ci.org/ARTbio/GalaxyKickStart/builds/246513378#L2695

It looks like some eggs are missing or not well installed, but I do not exclude a problem with the new VM Travis releases.

I understood that there is a new way to perform bioblend tests using Make and Makefile and I'll try to adopt it.

In the meantime, if anyone has thoughts about this, they are welcome ! I suspect that some of you could have run in this type of issues with repo travis test using bioblend-master ?

**Comment by mvdbeek** [comment]
So I think the best way to run the Galaxy related bioblend tests is the --undocumented-- new `bioblend-galaxy-tests` entrypoint added in https://github.com/galaxyproject/bioblend/pull/209. I have tried implementing that [here](https://github.com/ARTbio/GalaxyKickStart/pull/249). Let's see how far we can get there.

**Comment by nsoranzo** [comment]
@mvdbeek Is that also solved by https://github.com/galaxyproject/bioblend/pull/238 ?

**Comment by mvdbeek** [comment]
I think it was a matter of missing dependencies, since we installed the dependencies manually.

**Comment by drosofff** [comment]
@nsoranzo @mvdbeek yes it totally solved the issue.  Thank you all !
