### ISSUE TITLE
Including test data with bioblend install

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/bioblend#237]
I was trying to setup the new `bioblend-galaxy-tests` script for https://github.com/ARTbio/GalaxyKickStart, but running the full test suite failed because https://github.com/galaxyproject/bioblend/tree/master/bioblend/_tests/data is not included when installing bioblend (`pip install bioblend`).

**Comment by bgruening** [comment]
Using github works in galaxy-docker and in flavor testing like here: https://github.com/galaxyproject/galaxy-flavor-testing/blob/master/Makefile#L45

**Comment by mvdbeek** [comment]
You're using the locally cloned data.
This could all be replaced like so: https://github.com/ARTbio/GalaxyKickStart/pull/249/files

**Comment by drosofff** [comment]
@bgruening 

> Using github works in galaxy-docker and in flavor testing like here: https://github.com/galaxyproject/galaxy-flavor-testing/blob/master/Makefile#L45

I've been puzzled by this ! I would be curious to see whether the test still passes

**Comment by bgruening** [comment]
@mvdbeek Yes this gives us more flexibility to use different branches and forks, we can not wait for a new release if something breaks. 
@drosofff lastest test passed 3 days ago https://travis-ci.org/bgruening/docker-galaxy-stable/builds/244726177 before Docker package changed it's name again :(

**Comment by bgruening** [comment]
Test just passed on master, 17.05: https://travis-ci.org/bgruening/docker-galaxy-stable/builds/246565954

**Comment by bgruening** [comment]
But wait, I have disables a few tests, maybe your is under this blacklisted ones ... sorry in my phone.

**Comment by mvdbeek** [comment]
> @mvdbeek Yes this gives us more flexibility to use different branches and forks, we can not wait for a new release if something breaks.

`pip install https://github.com/galaxyproject/<username>/archive/<branch/tag>.zip` should work in that case, no?
This is just a lot less boilerplate code.

Also this is only peripherally related to the failing tests @drosofff is mentionning?

**Comment by bgruening** [comment]
@mvdbeek I'm not sure if this is related, I was just pointing out that these tests are working and you might want to take a loot?
You can redo everything, if its simpler cool, I'm just saying that these tests are working and usually I have a reason why I do it this way. For example you can not reuse all tests 1to1 from bioblend. Galaxy Docker uses Slurm, htcondor, SGE and you need to have different timeouts for a few tests. For some time I maintained my own fork but then decided that a few tests can just be skipped and this is easier with tox imho.

**Comment by mvdbeek** [comment]
> @mvdbeek I'm not sure if this is related, I was just pointing out that these tests are working and you might want to take a loot?

That was never the question, I'm sure the tests are working fine :)

> this is easier with tox imho.

I haven't looked into that yet, but i'd be surprised if this was difficult.

In any case we are already distributing the test data in the tarball, we're just not installing them, we have a nice entrypoint script whose purpose is exactly what I want to do here ... we can even test the test script.
