### ISSUE TITLE
get_libraries deleted flag not working properly

### ISSUE THREAD

**Issue by emartchenko** [galaxyproject/bioblend#239]
Using bioblend version 0.9.0, galaxy release 17.05

get_libraries() returns all libraries, including those that have been deleted
get_libraries(deleted=False) also returns all libraries, including deleted ones
get_libraries(deleted=True) returns only deleted libraries

**Comment by nsoranzo** [comment]
Fixed in #273. Now:
- `get_libraries()` and `get_libraries(deleted=False)` return only non-deleted libraries
- `get_libraries(deleted=True)` returns only deleted libraries (for admins only)
- `get_libraries(deleted=None)` returns all libraries (for admins only)
