### ISSUE TITLE
export_history: Uncaught exception in exposed API method

### ISSUE THREAD

**Issue by aghozlane** [galaxyproject/bioblend#240]
Dear Bioblend developpers,
I am experimenting an issue with the export_history function. Since I added to my galaxy workflow a new step that takes the results from 14 other steps, I am unable to download the results in my history.
Every time that I run the function export_history, I get the following error:

`>>> gi.histories.export_history("79966582feb6c081", wait=True)  
Traceback (most recent call last):  
  File "<stdin>", line 1, in <module>  
  File "/usr/local/lib/python3.5/dist-packages/bioblend/galaxy/histories/__init__.py", line 519, in export_history  
    r = Client._put(self, {}, url=url, params=params)  
  File "/usr/local/lib/python3.5/dist-packages/bioblend/galaxy/client.py", line 170, in _put
    return self.gi.make_put_request(url, payload=payload, params=params)  
  File "/usr/local/lib/python3.5/dist-packages/bioblend/galaxyclient.py", line 178, in make_put_request
    body=r.text, status_code=r.status_code)  
bioblend.ConnectionError: Unexpected HTTP status code: 500: {"err_msg": "Uncaught exception in exposed API method:", "err_code": 0}`

Any idea ?

**Comment by mvdbeek** [comment]
Do you have command-line access to the server that you interact with ? In that case you should see the corresponding error in the galaxy logs. Those would be helpful (and it's not unlikely that this is actually a galaxy bug).

**Comment by aghozlane** [comment]
Yes it's a local install. Here is the galaxy log:

galaxy.web.framework.decorators ERROR 2017-07-24 10:14:54,089 Uncaught exception in exposed API method:
Traceback (most recent call last):
  File "/home/aghozlan/galaxy/lib/galaxy/web/framework/decorators.py", line 282, in decorator
    rval = func( self, trans, *args, **kwargs )
  File "/home/aghozlan/galaxy/lib/galaxy/webapps/galaxy/api/histories.py", line 450, in archive_export
    self.queue_history_export( trans, history, gzip=gzip, include_hidden=include_hidden, include_deleted=include_deleted )
  File "/home/aghozlan/galaxy/lib/galaxy/web/base/controller.py", line 393, in queue_history_export
    history_exp_tool.execute( trans, incoming=params, history=history, set_output_hid=True )
  File "/home/aghozlan/galaxy/lib/galaxy/tools/__init__.py", line 1389, in execute
    return self.tool_action.execute( self, trans, incoming=incoming, set_output_hid=set_output_hid, history=history, **kwargs )
  File "/home/aghozlan/galaxy/lib/galaxy/tools/actions/history_imp_exp.py", line 124, in execute
    include_deleted=incoming[ 'include_deleted' ] )
  File "/home/aghozlan/galaxy/lib/galaxy/tools/imp_exp/__init__.py", line 506, in setup_job
    jobs_attrs_out.write( dumps( jobs_attrs, cls=HistoryDatasetAssociationEncoder ) )
  File "/usr/lib/python2.7/json/__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/home/aghozlan/galaxy/lib/galaxy/tools/imp_exp/__init__.py", line 385, in default
    return json.JSONEncoder.default( self, obj )
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <galaxy.model.HistoryDatasetCollectionAssociation object at 0x7f1f54524890> is not JSON serializable
127.0.0.1 - - [24/juil./2017:10:14:52 +0200] "PUT /api/histories/79966582feb6c081/exports?gzip=True&key=f293dce7785a77c338db9e8b8df9922c&include_hidden=False&include_deleted=False HTTP/1.1" 500 - "-" "python-requests/2.9.1"

**Comment by mvdbeek** [comment]
OK, that's probably a galaxy bug. Can you confirm that manually exporting the history in the UI fails as well ? Is there an empty dataset collection in that history, or a dataset collection with failed datasets ?

**Comment by aghozlane** [comment]
Yes, it's a galaxy bug. I confirm that I am unable to export the history manually. I have the following error:
Error - <type 'exceptions.TypeError'>: <galaxy.model.HistoryDatasetCollectionAssociation object at 0x7f1f8a0beb10> is not JSON serializable
URL: http://127.0.0.1:8080/history/export_archive?preview=True
File '/home/aghozlan/galaxy/lib/galaxy/web/framework/middleware/error.py', line 154 in __call__
  app_iter = self.application(environ, sr_checker)
File '/home/aghozlan/galaxy/.venv/local/lib/python2.7/site-packages/paste/recursive.py', line 85 in __call__
  return self.application(environ, start_response)
File '/home/aghozlan/galaxy/.venv/local/lib/python2.7/site-packages/paste/httpexceptions.py', line 640 in __call__
  return self.application(environ, start_response)
File '/home/aghozlan/galaxy/lib/galaxy/web/framework/base.py', line 134 in __call__
  return self.handle_request( environ, start_response )
File '/home/aghozlan/galaxy/lib/galaxy/web/framework/base.py', line 193 in handle_request
  body = method( trans, **kwargs )
File '/home/aghozlan/galaxy/lib/galaxy/webapps/galaxy/controllers/history.py', line 1226 in export_archive
  self.queue_history_export( trans, history, gzip=gzip, include_hidden=include_hidden, include_deleted=include_deleted )
File '/home/aghozlan/galaxy/lib/galaxy/web/base/controller.py', line 393 in queue_history_export
  history_exp_tool.execute( trans, incoming=params, history=history, set_output_hid=True )
File '/home/aghozlan/galaxy/lib/galaxy/tools/__init__.py', line 1389 in execute
  return self.tool_action.execute( self, trans, incoming=incoming, set_output_hid=set_output_hid, history=history, **kwargs )
File '/home/aghozlan/galaxy/lib/galaxy/tools/actions/history_imp_exp.py', line 124 in execute
  include_deleted=incoming[ 'include_deleted' ] )
File '/home/aghozlan/galaxy/lib/galaxy/tools/imp_exp/__init__.py', line 506 in setup_job
  jobs_attrs_out.write( dumps( jobs_attrs, cls=HistoryDatasetAssociationEncoder ) )
File '/usr/lib/python2.7/json/__init__.py', line 251 in dumps
  sort_keys=sort_keys, **kw).encode(obj)
File '/usr/lib/python2.7/json/encoder.py', line 207 in encode
  chunks = self.iterencode(o, _one_shot=True)
File '/usr/lib/python2.7/json/encoder.py', line 270 in iterencode
  return _iterencode(o, 0)
File '/home/aghozlan/galaxy/lib/galaxy/tools/imp_exp/__init__.py', line 385 in default
  return json.JSONEncoder.default( self, obj )
File '/usr/lib/python2.7/json/encoder.py', line 184 in default
  raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <galaxy.model.HistoryDatasetCollectionAssociation object at 0x7f1f8a0beb10> is not JSON serializable

There is no empty dataset collection.

**Comment by mvdbeek** [comment]
I have opened an issue on the galaxy repo, feel free to comment there. If we fix this there it should also work in bioblend.
