### ISSUE TITLE
specify name to paste_content method

### ISSUE THREAD

**Issue by xgaia** [galaxyproject/bioblend#242]
Hello!

I am using bioblend to create a new dataset in an history. For this, I use the [past_content](https://bioblend.readthedocs.io/en/latest/api_docs/galaxy/all.html#bioblend.galaxy.tools.ToolClient.paste_content) method.

Why we can't specify a file_name instead of the default "Pasted Entry" ? (like `upload_file`)

Currently, I have to write the data in a temporary file and use the upload_file method.

Regards

**Comment by nsoranzo** [comment]
@xgaia Actually that was a bug in the documentation, it is possible to specify the `file_name` parameter. The only caveat is that if you paste a list of URLs to upload, then Galaxy will create the corresponding datasets all with the same name.
