### ISSUE TITLE
Expose database ids

### ISSUE THREAD

**Issue by lecorguille** [galaxyproject/bioblend#245]
It should be great for debugging purpose if the different results from `show_*` can expose the database ids: history, hda, dataset ... 
It will be easier to make the mapping between the API and the real world (and eventually for dataset case, find the file path)

**Comment by nsoranzo** [comment]
@lecorguille Do you mean decode the encoded ids? You can do it using https://github.com/galaxyproject/galaxy/blob/dev/scripts/secret_decoder_ring.py , not sure this is something we should do in BioBlend, ping @jmchilton @erasche.

**Comment by jmchilton** [comment]
I don't have objections in terms of security - this encoding doesn't really add much in terms of security. It would just be difficult to do this throughout on the Galaxy side - we'd have to change both how things are consumed and produced throughout Galaxy. bioblend is much more uniform - one could imagine passing the secret key into the client and have this magically applied to all requests and responses on the client side. It would still be a bit of work though - probably best to stick with the secret decoder ring?

**Comment by lecorguille** [comment]
Even if it should be more confortable to get those decoded ids using directly bioblend, your trick, @nsoranzo works.
Many thanks
