### ISSUE TITLE
[Feature Request] Rename datasets in data libraries

### ISSUE THREAD

**Issue by alexlenail** [galaxyproject/bioblend#255]
Hi BioBlend Developers, 

I'd like to be able to rename datasets in data libraries. I know this is possible, because there's a Galaxy UI for doing this one dataset at a time: 

<img width="1031" alt="screen shot 2017-12-21 at 11 29 14 am" src="https://user-images.githubusercontent.com/2761597/34271676-35a5c692-e642-11e7-8ca4-8d61b4145993.png">

However, I'd like to do this for hundreds of files. As far as I can tell, this is an API Galaxy has, but not a function in bioblend. What would it take to add that function? Or is there a way to change file names I'm not aware of? 

Thanks!

**Comment by zfrenchee** [comment]
(this is possibly related to #243)

**Comment by martenson** [comment]
The API for this is fairly new, so bioblend has not been updated to wrap it yet I think.

**Comment by zfrenchee** [comment]
@martenson this feature would make a big difference to me!

**Comment by martenson** [comment]
@zfrenchee if you are in a hurry you can call the API directly (bypassing bioblend)

**Comment by nuwang** [comment]
So Martin's reply confirms that the method I suggested earlier over e-mail may be the only option.
That is, make a POST request to: http://<galaxy_server>/datasets/<dataset_id>/edit

with the values being:
```
name:test name
info:
annotation:
dbkey:?
save:Save
```

**Comment by zfrenchee** [comment]
@nuwang thanks for the details! As mentioned, since I'm running 17.05 I'm not sure that API even exists in my galaxy. Could we make it a goal to add a BioBlend method for this API by the time [18.01 comes out](https://github.com/galaxyproject/galaxy/issues/4920)?

**Comment by simonbray** [comment]
Was fixed in https://github.com/galaxyproject/bioblend/pull/267.
