### ISSUE TITLE
[Feature Request]: Uninstall Repository

### ISSUE THREAD

**Issue by alexlenail** [galaxyproject/bioblend#260]
Thanks to @mvdbeek , there is now a tool-removal API in galaxy: 

https://github.com/galaxyproject/galaxy/commit/67c66861c50f02475e497aa0c4feec7dfa16c2c2

As discussed in [this issue](https://github.com/galaxyproject/ephemeris/issues/83), it may make sense to add a bioblend tool uninstall endpoint, perhaps somewhere in this file:

https://github.com/galaxyproject/bioblend/blob/856db94ef09ad6cb026c2ed5b58c1a744cb9c641/bioblend/galaxy/toolshed/__init__.py

Maybe `uninstall_repository_revision` parallel to 

https://github.com/galaxyproject/bioblend/blob/856db94ef09ad6cb026c2ed5b58c1a744cb9c641/bioblend/galaxy/toolshed/__init__.py#L62-L68

**Comment by mvdbeek** [comment]
I've taken the liberty to change this to Repository, tool installation/uninstallation is not yet possible,(though that would be cool to have).
