### ISSUE TITLE
Giving workflow parameters to workflow

### ISSUE THREAD

**Issue by mmeier93** [galaxyproject/bioblend#274]
Hi, I am trying to use bioblend to run a workflow and I would like to give it parameters with params. I made the workflow in the GUI and put some parameters "set at runtime". 

I have succeeded in giving a parameters for one parameter, but not for multiple ones. Would it be possible to get an example on how to set multiple parameters?

I posted my question on the Galaxy help forum but I haven't had a reply and I am desperate to find a solution. Here is my post:
https://help.galaxyproject.org/t/giving-workflow-parameters-to-bioblend-params/495/3

**Comment by nsoranzo** [comment]
I've replied in the post, let's keep the discussion there.
