### ISSUE TITLE
<repeat > Parameters don't get passed correctly on invoke_workflow for step

### ISSUE THREAD

**Issue by pcm32** [galaxyproject/bioblend#278]
I have a case of a tool: https://github.com/ebi-gene-expression-group/container-galaxy-sc-tertiary/blob/develop/tools/tertiary-analysis/scanpy/scanpy-filter-cells.xml#L31

which gets executed as part of our workflows. When I send it to execute via bioblend invoke_workflow, what I notice is that the parameters map given doesn't get set for the tool on the workflow execution. For the indicated part above we are passing the following element as part of the params dictionary given to invoke workflow:

```
<step_num>: {
"parameters": [
      {
        "__index__": 0,
        "min": "0.0",
        "name": "n_cells",
        "max": "1000000000.0"
      },
      {
        "__index__": 1,
        "min": "0.0",
        "name": "n_counts",
        "max": "1000000000.0"
      }
    ]
}
```

is this how it should be passed for a repeat or I'm missing something? Thanks! This resembles at least the structure I see from the same workflow when shown by bioblend (show workflow). 

The execution doesn't fail, is just that the parameters given are ignored giving preference to the default parameters set in the workflow itself.

Thanks!

**Comment by pcm32** [comment]
Ok, after further investigation I noticed that the workflow provided to the invoke_workflow method needs to have at least `n` parameters set in the repeat for `n` parameters to be settable via the parameters construct given to invoke_workflow. So, in the case above, `n_counts` (the second parameter) will only get set if the workflow used, through the UI, had the repeat expanded to have at least two slots. This is probably a a Galaxy API bug.

**Comment by nsoranzo** [comment]
@jmchilton @mvdbeek Do you know if there's a way around this?

**Comment by mvdbeek** [comment]
I don't think you can add repeats at workflow run time since the repeat can alter the structure of the workflow. The same is true for switching conditionals. See https://github.com/galaxyproject/galaxy/issues/4528 for a discussion, we do need to address this.

**Comment by pcm32** [comment]
I think that this is partly mitigated now by explanation in the documentation #279, but up to you if you want to close this or not really. Thanks for the help!

**Comment by nsoranzo** [comment]
Closing, since this is not a BioBlend issue any way.
