### ISSUE TITLE
Creating a collection, workflow, api calls, and performance

### ISSUE THREAD

**Issue by joachimwolff** [galaxyproject/bioblend#281]
Hi,

I have created a collection out of history items. It is possible to this with current bioblend, however, it is not intuitive and really slow. Some short remarks on how I did this, maybe there is a way you can optimize the API. 

First, you need to receive the dataset ids. This can be done via:
```dataset_ids = gi.histories.show_history(id_history)['state_ids']['ok']```
It works, but a) it is really not intuitive to get first a really big dictionary from the server and selecting locally over the keys 'state_ids' and there the status 'ok' the ids of the datasets of a history. Why not providing an API function 'receive_all_dataset_ids' and getting a list of ids back? And b) it is not documented on readthedocs you are able to receive the datasets ids in this way. Without the help of @erasche I wouldn't been able to get this information. And not everyone is having an experienced Galaxy admin sitting in the next office down the hallway.

In my second step I had to order the files by name locally to create two collections: for forward (R1) and reverse (R2) strand files.

```
element_identifiers_r1 = []
element_identifiers_r2 = []
for dataset_id in dataset_ids:
    dataset_dict = gi.histories.show_dataset(id_history, dataset_id)
    if '_R1.' in dataset_dict['name']:
        element_identifiers_r1.append(dataset_dict)
    elif '_R2.' in dataset_dict['name']:
        element_identifiers_r2.append(dataset_dict)

```
Again, it seems not to be intuitive to download each history item one by one with all metadata and using there only the name field. However, I need the full dict to be able to create a collection:

```
collection_description_r1 = {'collection_type': 'list',
 'element_identifiers': element_identifiers_r1,
 'name': 'Forward reads'}
collection_description_r2 = {'collection_type': 'list',
 'element_identifiers': element_identifiers_r2,
 'name': 'Reverse reads'}
``` 

And again, why do I need to download the full metadata information? It would be more intuitive for me as follows:

1. Download all ids + names and only them. This means there need to be two more API functions: Get dataset_ids and get_dataset_names. The order of the elements in the two lists needs to be guaranteed.
2. Instead of a list of dictionaries `element_identifiers` a list of dataset ids would be sufficient. All the rest can be handled on the server side.

And last, to create a new collection:
```gi.histories.create_dataset_collection(id_history, collection_description_r1)```
This is a simple call, however it took for ~4000 elements that should be part of the new collection ~20 - 30 mins with usegalaxy.eu server. (Sorry I cannot re-measure it atm, because the server is down).

After this collection was created, I wanted to check if everything worked as expected. Unfortunately there is only a undocumented way to receive the collection ids. Again @erasche showed me this, but why not add a new API call `get_collection_ids`?

Best,

Joachim

**Comment by mvdbeek** [comment]
Let me try to break this down a little:

> Why not providing an API function 'receive_all_dataset_ids' and getting a list of ids back?

You mean `gi.histories.show_history('847f7c7732a972ca', contents=True)` ?
This returns a list of history items. If you want only HDAs, the idea is to use
`gi.histories.show_history('847f7c7732a972ca', contents=True, types=['dataset'])`.
If you only want collections, use
`gi.histories.show_history('847f7c7732a972ca', contents=True, types=['dataset_collection'])`.

Unfortunately that is broken in bioblend, and the documentation is missing too, so for now the type filter doesn't work.
Still, you'd get a list of items like this:
```
 {'history_content_type': 'dataset',
  'update_time': '2019-02-07T15:36:14.914210',
  'name': 'fastp on data 213 and data 212',
  'extension': 'fastqsanger.gz',
  'type_id': 'dataset-cdc24be666e7be1a',
  'deleted': False,
  'history_id': '847f7c7732a972ca',
  'tags': [],
  'id': 'cdc24be666e7be1a',
  'visible': False,
  'state': 'new',
  'create_time': '2019-02-07T15:36:14.633549',
  'hid': 999,
  'url': '/api/histories/847f7c7732a972ca/contents/cdc24be666e7be1a',
  'dataset_id': 'f9f62bc727e0dff8',
  'type': 'file',
  'purged': False}
```
For a history with 6000 items that took 2 seconds, and it's straightforward to filter this to your liking.

Creating the collection shouldn't take that long, but I haven't done this in some time. We may be able to optimize this in Galaxy.

**Comment by joachimwolff** [comment]
It is nice to hear that 'somehow' the requested functions do exists. 

Attached is a screenshot of the documentation. I don't know how anyone could be able to make the calls you have shown with this. Especially I want to point out `types(str) ???`:

![bioblend_api](https://user-images.githubusercontent.com/13435136/57368314-26642180-718b-11e9-8a8c-077079da5be9.png)

**Comment by mvdbeek** [comment]
> I don't know how anyone could be able to make the calls you have shown with this.

The type parameter can be improved. If you have a suggestion for the contents parameter let us know.
