### ISSUE TITLE
Adding tags to many history items

### ISSUE THREAD

**Issue by joachimwolff** [galaxyproject/bioblend#282]
Hi,

I needed to create a name tag for ~8000 history items on usegalaxy.eu server. This is possible to do with bioblend, but is non-intuitive and really slow.

My task was to take the name of an item and re-use it as a tag. To do so I have to:

1. Download all ids of the datasets and with them all names:
```
dataset_ids = []
dataset_ids = gi.histories.show_history(id_history)['state_ids']['ok']
for dataset in dataset_ids:
    names_list.append(gi.histories.show_dataset(id_history, dataset)['name'])
```

This is some overhead, and, as written in my other issue opend today, it would be an improvement if an API call to receive the ids and dataset names would exists and I don't have to download all metadata.

2. Add a tag. This is more complicated than I thought. There is this `update_dataset` function but it is not well documented. Once more I had to ask @erasche if I just can write 'tag' as a parameter.Moreover, I wanted to have tags which are inherited and shown in the GUI, in the GUI you can use the hashtag for this `#foo`. Not so in the API, there it needs to be `name:foo`. Again, this is not documented and non-intuitive. Please remove multiple ways to achieve the same result. 

The following code I used:

```
for data_id, name in zip(dataset_ids, names_list):
    gi.histories.update_dataset(id_history, data_id, tags=['name:'+name])
```
Finally, the call of the update function to add ~8000 tags is slow, really slow. With usegalaxy.eu server it took 1 - 2 hours! This performance is not acceptable.

I propose the following API function:
```
add_tag(dataset_id, tag=['', '',], add_as_name_tag=True)
```

Or, for many dataset_ids at once:

```
add_tag(dataset_id_list=[id1, id2, ..., id_n], tag=[['', '',], [],....[]], add_as_name_tag=True)
```

 Best,

Joachim

**Comment by mvdbeek** [comment]
Tags being slow is not a bioblend issue, they require two database flushes per operation. Also keep in mind that they are **absolutely not** a replacement for dataset names or collection identifiers. They will get garbled up as soon as you have a tool that takes multiple separate inputs or when you run a tool that consume multiple datasets.
`#` and `name:` not being equivalent is a Galaxy issue too.

We can add a convenience function to set tags in bioblend, sure.

**Comment by erasche** [comment]
> They will get garbled up as soon as you have a tool that takes multiple separate inputs or when you run a tool that consume multiple datasets.

They do?

**Comment by mvdbeek** [comment]
Yep. I'd only gather some metadata top-level stats with name tags, everything else is going to break down with medium complexity analyses. Some examples are in https://github.com/galaxyproject/galaxy/issues/3730, and we have an issue where we discuss this in more detail, but I can't find it :(.

Turns out naming things is not easy ...

**Comment by mvdbeek** [comment]
was looking for https://github.com/galaxyproject/galaxy/issues/4212

**Comment by erasche** [comment]
It may be the case for your medium complexity analyses, but for other user's medium complexity analyses I'd argue that propagating tags are still useful to users even if they get "garbled", and we shouldn't place unnecessary restrictions on their use.

So we're left with action items of:

- a bulk tag assignment API would be helpful, if this can decrease number of flushes
- `#` and `name:` not being equivalent
- bioblend could use a convenience API for setting tags perhaps

**Comment by dannon** [comment]
>     1. Not so in the API, there it needs to be `name:foo`. Again, this is not documented and non-intuitive. Please remove multiple ways to achieve the same result.

We should definitely document this better in the API.  Some background here is that the '#' is just a unique display mechanism and input convenience for 'name' keyed key:value hierarchical tags that already existed in Galaxy.   In the UI we just do something like: https://github.com/galaxyproject/galaxy/blob/dev/client/galaxy/scripts/components/Tags/model.js#L11

Originally I didn't want to push any 'display specific' logic (the `#` `name:` alias) into the core tags model/APIs, but we could revisit this.  Or we could just document it better.

**Comment by erasche** [comment]
https://docs.galaxyproject.org/en/master/api/api.html#galaxy.webapps.galaxy.api.history_contents.HistoryContentsController.update is probably lacking some information and hard to find for users (more so than in bioblend, just via grepability). 

Following the link for 

> a dictionary containing any or all the fields in galaxy.model.HistoryDatasetAssociation.to_dict() and/or the following:

Where 'tags' is not a readily apparent value you could send.
