### ISSUE TITLE
Is bioblend concurrency safe?

### ISSUE THREAD

**Issue by pcm32** [galaxyproject/bioblend#286]
We are running some pipelines through bioblend on Galaxy. Basically our setup loads workflow file, parameters and data into the instance and then waits until the workflow is done (all through bioblend). When we increase the number of concurrent requests sent to the Galaxy instance we get errors that we cannot reproduce when just running a single run on its own. We are wondering if there might be communication issues when doing multiple concurrent runs?

If we work with 10 concurrent workflows being executed, then we don't seem to see the error, but when we move to 20 concurrent executions, we see it.

Maybe it could be an issue with our workflow resolution logic (how do we decide when the workflow is done). If you could give us any advice, it would be great:

https://github.com/ebi-gene-expression-group/galaxy-workflow-executor/blob/feature/consider_paused_jobs_due_to_previous_errors/run_galaxy_workflow.py#L407-L413

The error we see is that the part shown there is lead to believe that all jobs are in "terminal" states when in fact jobs are still running. We don't see this if just sending one or a few executions at the same time (with the same failing datasets).

Thanks!

**Comment by nsoranzo** [comment]
I don't think BioBlend has any concurrency issue itself (it's just a thin layer over the Galaxy API). Regarding your code, before checking the state of datasets in the history, I'd check that the workflow invocation is completed using [show_invocation()](https://bioblend.readthedocs.io/en/latest/api_docs/galaxy/all.html#bioblend.galaxy.workflows.WorkflowClient.show_invocation) in a loop. Otherwise new datasets may still be added to the history after you checked its state.

**Comment by pcm32** [comment]
Thanks @nsoranzo for the advice... would you be looking at `state` in the `show_invocation()` result? I think I was once here, but it wasn't clear to me whether the invocation state could indicate that all jobs in the workflow where done. My understanding from the galaxy code is:

```
    states = Bunch(
        NEW='new',  # Brand new workflow invocation... maybe this should be same as READY
        READY='ready',  # Workflow ready for another iteration of scheduling.
        SCHEDULED='scheduled',  # Workflow has been scheduled.
        CANCELLED='cancelled',
        FAILED='failed',
    )
```
so which one of those states mean that the workflow is completed? `READY` and `FAILED` I would assume? Or is `READY` also the state acquired once it is not `NEW` anymore? Thanks!

**Comment by nsoranzo** [comment]
`scheduled`, `cancelled` and `failed` are the terminal states, with the first one indicating a successful invocation.

**Comment by pcm32** [comment]
ahh, great, thanks!
