### ISSUE TITLE
'GalaxyInstance' object has no attribute 'toolshed'

### ISSUE THREAD

**Issue by mpaya** [galaxyproject/bioblend#288]
I want to automatically populate a Galaxy instance. Following BioBlend docs, I had no issue with other commands, but when trying to install a toolshed repository I cannot have it work as the rest. I tried before ephemeris and ansible-playbook for tool installation, but they are bugged with connection errors and fail [(issue)](https://github.com/galaxyproject/ephemeris/issues/99), so I wanted to try this way. This is some code I used:
```
from bioblend import galaxy
gi = galaxy.GalaxyInstance(url='http://127.0.0.1:8080', key='admin')
hist1 = gi.histories.create_history(name='hist1')  # works

gi.workflows
# <bioblend.galaxy.workflows.WorkflowClient object at 0x7f4b0943e950>
gi.toolshed
# AttributeError: 'GalaxyInstance' object has no attribute 'toolshed'
```
Using `inspect.getmembers(galaxy)`, I see the module `toolshed`, but I cannot have it working. I'd appreciate some help.

I tried on bioblend 0.11.0 and 0.12.00, installed with pip. Running on a dockerized Galaxy, version 18.05.

**Comment by nsoranzo** [comment]
@mpaya Thanks for the report. I think `gi.toolShed` should work (note the capital S). Admittedly it's not very consistent with how we name object attributes or with PEP8, I will add an alias `gi.toolshed` in the next BioBlend release.

**Comment by mpaya** [comment]
Thanks for the fix, it worked, although it still cannot install the tool.

```
gi.toolShed
<bioblend.galaxy.toolshed.ToolShedClient object at 0x7f4b093d8890>

tool_shed_url = "https://toolshed.g2.bx.psu.edu"
name = 'suite_samtools_1_2'
owner = 'devteam'
changeset_revision = '5b673ccc8747'
label = 'SAMtools'

gi.toolShed.install_repository_revision(tool_shed_url, name, owner, changeset_revision, install_tool_dependencies=True, install_repository_dependencies=True, install_resolver_dependencies=True, tool_panel_section_id=None, new_tool_panel_section_label=label)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/bioblend/galaxy/toolshed/__init__.py", line 146, in install_repository_revision
    return self._post(url=url, payload=payload)
  File "/usr/local/lib/python2.7/dist-packages/bioblend/galaxy/client.py", line 152, in _post
    files_attached=files_attached)
  File "/usr/local/lib/python2.7/dist-packages/bioblend/galaxyclient.py", line 137, in make_post_request
    timeout=self.timeout)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 112, in post
    :return: :class:`Response <Response>` object
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    # cases, and look like a memory leak in others.
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 512, in request
    data=data or {},
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 622, in send
    # Set defaults that the hooks can utilize to ensure they always have
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 495, in send
    raise
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))
```
Do you know if this may be related to this bioblend module and/or is fixable? 

Thank you!!
Miriam

**Comment by nsoranzo** [comment]
@mpaya Can you try with a single tool instead of a suite? When installing many tools and/or large dependency sets, the request seems to fail while it's still being processed by Galaxy.

Also, you may want to take a look at [ephemerics](https://ephemeris.readthedocs.io/), which wraps this functionalities in easier-to-use scripts.

**Comment by mpaya** [comment]
I already tried with ephemeris and the ansible playbook on many tools, both suites (deeptools, picard, samtools, bedtools...) and single tools. The error was random, e.g. bedtools had no issue, but macs2, htseq and deseq2 displayed the same error but they are working. There are different behaviors with the wrappers, ephemeris will stop at the first error while the playbook will go on through all tools, allowing full installation of the tool list. I'll follow your advice and avoid suites that may crash.
Thanks.
