### ISSUE TITLE
Release schedule

### ISSUE THREAD

**Issue by erasche** [galaxyproject/bioblend#293]
Would it be possible to consider releasing more regularly, perhaps in sync with the Galaxy releases? Ok, not many new features since last release, but it would ensure that changes are in a release within 3 months, rather than having to specially request a release.

**Comment by nsoranzo** [comment]
It's a good point, we had 2 releases per year in 2017 and 2018 (Galaxy has 3), but none in 2019 yet. I'll start drafting one now, but giving the limited time I have for BioBlend, I cannot promise to do regular releases. Help welcome though!

**Comment by erasche** [comment]
Sure, my thinking was if we release in coordination with Galaxy then maybe this task can be more shared amongst team members. Is there anything written about what is involved in a release?

**Comment by nsoranzo** [comment]
It's mostly:
- for major releases, remove stuff (parameters, methods) deprecated in the previous cycle
- update the `__version__` in `bioblend/__init__.py`
- curate the `CHANGELOG.md`
- commit the changes above, push, and wait for TravisCI tests to pass
- make a release through the GitHub interface
- run `make release` to upload to PyPI
- optionally update the bioconda package at https://github.com/bioconda/bioconda-recipes/blob/master/recipes/bioblend/meta.yaml

**Comment by nsoranzo** [comment]
@erasche Should I add the above list to a `CONTRIBUTING.md` ? Not sure if there is any other standard place to document this.

**Comment by erasche** [comment]
Sounds good. I looked around yesterday and didn't see anything obvious. That sounds like the best option.

**Comment by nsoranzo** [comment]
@erasche Cool, thanks for checking! I've added it in commit c9c45f2 .

**Comment by abretaud** [comment]
Hi!
Is there a plan for a new release anytime soon? No big hurry, just that 0.13 is almost 1 year old now, I did a `pip install bioblend` and spent a few minutes before realising that an [old PR](https://github.com/galaxyproject/bioblend/pull/296) of mine was just not released yet

**Comment by nsoranzo** [comment]
Yes, sorry, I am struggling with time at the moment, but I already started to compile the release notes for `CHANGELOG.md` and hope to finish ASAP, especially because I'd like to use the new release for the BCC2020 "Scripting Galaxy with BioBlend" training courses.

**Comment by abretaud** [comment]
Ok cool, good to know that it's coming, no worry :)

**Comment by nsoranzo** [comment]
@abretaud BioBlend 0.14.0 is finally out!

**Comment by abretaud** [comment]
Super cool, thanks Nicola!
