### ISSUE TITLE
Stop supporting Galaxy < 15.03

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/bioblend#304]
Galaxy 15.03 is the first release exposing its version through the API. Supporting only Galaxy releases for which we can determine the version would make it easier to work with changes in API endpoints and return values.

Opinions @galaxyproject/bioblend ?

**Comment by bgruening** [comment]
@nsoranzo :+1: from me! Cutting old hairs and move faster forward is good.

**Comment by mvdbeek** [comment]
👍
