### ISSUE TITLE
Potential dependency conflicts between bioblend and requests

### ISSUE THREAD

**Issue by NeolithEra** [galaxyproject/bioblend#310]
Hi, as shown in the following full dependency graph of  **_bioblend_**, **_bioblend_** requires **_requests >=2.20.0_** ， while the installed version of **_requests-toolbelt_**(0.9.1) requires _**requests >=2.0.1,<3.0.0**_.

According to Pip's _“first found wins”_ installation strategy, _**requests  2.22.0**_ is the actually installed version.  

Although the first found package version _**requests  2.22.0**_ just satisfies the later dependency constraint （_**requests >=2.0.1,<3.0.0**_), it will lead to a build failure once developers release a newer version of requests.

### Dependency tree--------
```
bioblend - 0.13.0
| +- boto(install version:2.49.0 version range:>=2.9.7)
| +- pyyaml(install version:5.2b1 version range:*)
| +- requests(install version:2.22.0 version range:>=2.20.0)
| | +- certifi(install version:2019.9.11 version range:>=2017.4.17)
| | +- chardet(install version:3.0.4 version range:<3.1.0,>=3.0.2)
| | +- idna(install version:2.8 version range:>=2.5,<2.9)
| | +- urllib3(install version:1.25.7 version range:<1.26,>=1.21.1)
| +- requests-toolbelt(install version:0.9.1 version range:>=0.5.1)
| | +- requests(install version:2.22.0 version range:>=2.0.1,<3.0.0)
| | | +- certifi(install version:2019.9.11 version range:>=2017.4.17)
| | | +- chardet(install version:3.0.4 version range:<3.1.0,>=3.0.2)
| | | +- idna(install version:2.8 version range:>=2.5,<2.9)
| | | +- urllib3(install version:1.25.7 version range:<1.26,>=1.21.1)
| +- six(install version:1.13.0 version range:*) 
```

Thanks for your attention.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Suggested Solution

1.	Fix your direct dependencies to be **_requests >=2.20.0 , <3_**.
2.	Ask your upstream project **_requests-toolbelt_** to lose the version range of **_requests_** to be **_>=2.0.1_**.

@nsoranzo Which solution do you prefer, 1 or 2?
Please let me know your choice. May I pull a request to solve this issue?

**Comment by nsoranzo** [comment]
@NeolithEra Thanks for the report. At the moment I don't feel the need to change the pinnings, especially given that it's not clear in which direction the development of `requests` is going.
