### ISSUE TITLE
get_invocations(), forward history_id param

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/bioblend#311]
gi.workflows.get_invocations() should forward the optional history_id parameter to allow a reverse lookup of invocation from history.

**Comment by nsoranzo** [comment]
Yep, the method signature could be extended to `gi.workflows.get_invocations(workflow_id=None, history_id=None, user_id=None, include_terminal=True, limit=None, view='collection', step_details=False)`

**Comment by simonbray** [comment]
Fixed in https://github.com/galaxyproject/bioblend/pull/371/.
