### ISSUE TITLE
Workflow.run() doesn't wait and doesn't return outputs

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/bioblend#317]
https://github.com/galaxyproject/bioblend/blob/c1a13cd7a3fa749754d0f7990bafcbfd1ee5421f/bioblend/galaxy/objects/wrappers.py#L460-L467

The api returns an empty 'outputs' dict in the invocation information. This causes this code to immediately exit the loop and produce an empty list.

The code needs to wait for the 'outputs' dict to become populated by Galaxy.

**Comment by nsoranzo** [comment]
I don't think that's possible with the current implementation of `Workflow.run()` in BioBlend.objects in case of a non-fixed number of outputs. For that we would need to wrap workflow invocations as objects, probably. See also https://github.com/galaxyproject/bioblend/issues/171 .

**Comment by innovate-invent** [comment]
I am not sure what you mean by 'non-fixed number of outputs'. My workflow creates the same outputs regardless of the input.
