### ISSUE TITLE
Import workflows error

### ISSUE THREAD

**Issue by davidchristiany** [galaxyproject/bioblend#328]
I got an error while importing a workflow dictionary to Galaxy:
`bioblend.ConnectionError: Unexpected HTTP status code: 500: {"err_msg": "Uncaught exception in exposed API method:", "err_code": 0}`

I get all workflows from a Galaxy user with get_workflows()
I then tried to import a workflow to another Galaxy instance:
```
>>> wf
{'name': 'W4M: Mass spectrometry: LC-MS analysis', 'tags': ['metabolomics'], 'deleted': False, 'latest_workflow_uuid': 'f47e42ae-1d77-4bc8-86c4-c7000ae6e173', 'show_in_tool_panel': False, 'url': '/api/workflows/b4a9efd5c50010ba', 'number_of_steps': 19, 'published': False, 'owner': 'dchristiany', 'model_class': 'StoredWorkflow', 'id': 'b4a9efd5c50010ba'}
```
```
gi = galaxy.GalaxyInstance(url='http://127.0.0.1:8000', key='your_api_key')`
wfclient = galaxy.workflows.WorkflowClient(gi)
```
```
>>> wfclient.import_workflow_dict(wf)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/projet/maiage/save/dchristiany/.conda/envs/galaxy_test/lib/python3.8/site-packages/bioblend/galaxy/workflows/__init__.py", line 128, in import_workflow_dict
    return self._post(url=url, payload=payload)
  File "/projet/maiage/save/dchristiany/.conda/envs/galaxy_test/lib/python3.8/site-packages/bioblend/galaxy/client.py", line 172, in _post
    return self.gi.make_post_request(url, payload=payload,
  File "/projet/maiage/save/dchristiany/.conda/envs/galaxy_test/lib/python3.8/site-packages/bioblend/galaxyclient.py", line 131, in make_post_request
    raise ConnectionError("Unexpected HTTP status code: %s" % r.status_code,
bioblend.ConnectionError: Unexpected HTTP status code: 500: {"err_msg": "Uncaught exception in exposed API method:", "err_code": 0}
```

**Comment by mvdbeek** [comment]
> ```
> {'name': 'W4M: Mass spectrometry: LC-MS analysis', 'tags': ['metabolomics'], 'deleted': False, 'latest_workflow_uuid': 'f47e42ae-1d77-4bc8-86c4-c7000ae6e173', 'show_in_tool_panel': False, 'url': '/api/workflows/b4a9efd5c50010ba', 'number_of_steps': 19, 'published': False, 'owner': 'dchristiany', 'model_class': 'StoredWorkflow', 'id': 'b4a9efd5c50010ba'}
> ```

That is an overview of a workflow, as you see it in the workflow list. With the `id` of that workflow you can download the workflow using https://bioblend.readthedocs.io/en/latest/api_docs/galaxy/all.html#bioblend.galaxy.workflows.WorkflowClient.export_workflow_dict

**Comment by davidchristiany** [comment]
Thanks for the quick anwser, it worked just fine with the real workflows and not the overviews
