### ISSUE TITLE
BioBlend with CloudMan on Windows Azure?

### ISSUE THREAD

**Issue by lee212** [galaxyproject/bioblend#33]
Hi,

I was thinking that I might be able to provide a python library to support BioBlend with Cloudman on Windows Azure. The library has to use Windows SDK instead of boto to utilize Azure Virtual Machines but most features should be similar. More details should be described but by using [azure-sdk-for-python](https://github.com/WindowsAzure/azure-sdk-for-python/), it shouldn't be difficult.

What do you think? I would like to hear any thoughts and comments for that.

Thanks,
Hyungro

**Comment by afgane** [comment]
Old issue - if it emerges again can be revisited. Closing for now.
