### ISSUE TITLE
HTTP Authentication for Galaxy Server

### ISSUE THREAD

**Issue by mshamash** [galaxyproject/bioblend#332]
Hello,

Our Galaxy server is setup so that we must authenticate via HTTP basic authentication with a username/password for the system before we can actually access Galaxy and log in with our Galaxy user account. 

How can I specify this when defining a GalaxyInstance? Since without it, I get 401 Unauthorized error.

Thanks.

**Comment by hexylena** [comment]
Hi @mshamash, have you tried using a URL with the authentication information when configuring bioblend? e.g. `http://user:pass@my-server.edu/galaxy`

**Comment by mshamash** [comment]
> Hi @mshamash, have you tried using a URL with the authentication information when configuring bioblend? e.g. `http://user:pass@my-server.edu/galaxy`

Hi @hexylena,

Thank you for the suggestion. I tried that ant it worked perfectly! Appreciate it.
