### ISSUE TITLE
upload_from_galaxy_filesystem() jobs just stay queued forever in Galaxy

### ISSUE THREAD

**Issue by DanBerrios** [galaxyproject/bioblend#334]
I'm using Bioblend to mass-upload files from various files on the server in S3-mounted buckets into data libraries in our Galaxy system.  The files appear in the libaries, with correct sizes, but remain in "queued" state forever... they cannot be used in histories.  Any ideas why?  The "queued" jobs to upload each file have no assigned job runners.  Other job types run fine....

**Comment by nsoranzo** [comment]
@DanBerrios Thanks for the issue report. From your description this seems a Galaxy (not BioBlend) issue, unless you have any hint otherwise?

**Comment by DanBerrios** [comment]
@nsoranzo Thanks Nicola. Yes, it may be unrelated to Bioblend.  I guess I will re-post in Galaxy issues.

**Comment by nsoranzo** [comment]
Re-opened as https://github.com/galaxyproject/galaxy/issues/10081
