### ISSUE TITLE
[Request] Method to obtain History ID from a published History URL

### ISSUE THREAD

**Issue by mtekman** [galaxyproject/bioblend#339]
I was pointed to this solution by @mvdbeek via @simonbray

```
https://usegalaxy.eu/api/histories/published?q=slug&qv=<history-title>
```

but I found that it was too inexact, since if a user imports and republishes the history,  the request would match multiple items.

****** 

For now I use an inelegant solution below:

```python
def get_hid_from_public_url (hist_url):
    '''Return history ID for a public Galaxy URL.'''
    try:
        req = requests.get(hist_url, timeout=3)
    except requests.ConnectionError:
        print("Failed to get contents for url")
        sys.exit(-1)

    ## Search for history id in page source
    lines = str(req.content).splitlines()
    hhid = None
    for line in lines:
        if "data: {" in line:
            hhid = line.split(' id : ')[1].split('"')[1]
            break
    return hhid
```

But it would be great if there was a `Galaxyinstance.get_history_ids(url=,name=)` function

Thanks!

**Comment by mvdbeek** [comment]
slugs are unique

**Comment by simonbray** [comment]
https://usegalaxy.eu/u/sbray/h/slugtest, https://usegalaxy.eu/u/simonbray/h/slugtest

(yes, I know I technically shouldn't have two accounts... Björn and Mauro are aware though)

**Comment by nsoranzo** [comment]
I think that a good extension of the present API that would make this easier is to add a `published` parameter to the `HistoryClient.get_histories()` method, which could be used in combination with the `name` and `deleted` filters.

Let me know if that would be helpful and I can work on an implementation.

**Comment by simonbray** [comment]
> I think that a good extension of the present API that would make this easier is to add a published parameter to the HistoryClient.get_histories() method, which could be used in combination with the name and deleted filters.

I think this would definitely be nice to have. I guess being able to filter by `slug` and `user` would also be handy for @mtekman, though it seems the latter has been disabled in the API: https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/managers/sharable.py#L459

**Comment by simonbray** [comment]
I think this was fixed by https://github.com/galaxyproject/bioblend/pull/342? Please reopen if not @mtekman @nsoranzo.
