### ISSUE TITLE
Move CI to GitHub workflows

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/bioblend#347]

**Comment by bgruening** [comment]
@OlegZharkov do you want to look at this?

**Comment by OlegZharkov** [comment]
I will work on this

**Comment by nsoranzo** [comment]
Travis is really becoming an hindrance!

@OlegZharkov Can I help with that?

**Comment by OlegZharkov** [comment]
> Travis is really becoming an hindrance!
> 
> @OlegZharkov Can I help with that?

Hey, sorry, too many emails and I didn't see this one right away. I've been struggling a lot on Thursday.  Linting is already on gh-actions, it was quite easy to implement. I can create a PR for that, pretty much right away. 

For the test, it took me a while to configure the database and the preparation almost works. the latest problem, that I remember, is dealing with environment variables between steps ` >> $GITHUB_ENV` supposed to solve it. I hope to find time to finish this. 
I remember, that I wanted to put this variable as global var here: https://github.com/OlegZharkov/bioblend/blob/master/.github/workflows/test.yml#L67

**Comment by nsoranzo** [comment]
No worries, thanks for the reply! Maybe open a WIP PR with what you have till now?
