### ISSUE TITLE
Method to open a history in the browser

### ISSUE THREAD

**Issue by simonbray** [galaxyproject/bioblend#349]
Maybe it's just me with this use-case, but I find myself switching often between bioblend and the UI when I'm working. When dealing with thousands of histories it can be a bit of a pain to find the history in the UI which I was just working on in bioblend. It would be handy to have a `gi.histories.switch_to(history_id)` which I can just run, go to the browser window and refresh.

This needs a change to the Galaxy API but it's still simple enough to count as a paper cut.

**Comment by nsoranzo** [comment]
The Galaxy UI saves the current history in a cookie, so if you have Galaxy open on 2 different computers (or you can simulate that with a private browsing session) they can have 2 different current histories.

So I suspect this will be a wontfix.

Ping @dannon

**Comment by simonbray** [comment]
Okay, that's good to know. Then I agree it probably doesn't make sense.

**Comment by mvdbeek** [comment]
We can generate a URL with the history to go to though. We can already do that for published histories.

**Comment by simonbray** [comment]
Well, actually, `/histories/view?id={history_id}` works fine as well, though it's a bit annoying for the user to construct themselves.

**Comment by mvdbeek** [comment]
So bioblend could just do the platform-specifc opening of that URL ? With https://docs.python.org/3.8/library/webbrowser.html#webbrowser.open_new_tab for instance.

**Comment by simonbray** [comment]
There's also `/switch_to_history?hist_id={history_id}`.
