### ISSUE TITLE
[Documentation] Why the name "BioBlend"?

### ISSUE THREAD

**Issue by mtekman** [galaxyproject/bioblend#350]
Asked originally by @OlegZharkov, but I see this bit of vital history is missing in the docs

**Comment by afgane** [comment]
The library was originally called just `Blend` but renamed it to reflect more of its domain and a bit more unique so it can be easier to search. The name was intended to be short and easily pronounceable. In its original implementation, the goal was to provide a lot more support for CloudMan and other integration capabilities, allowing them to be _blended_ together. `Blend` fit the bill.

Added to the docs here: https://github.com/galaxyproject/bioblend/pull/357
