### ISSUE TITLE
BioBlend.objects examples need to be updated

### ISSUE THREAD

**Issue by gmauro** [galaxyproject/bioblend#353]
The BioBlend.objects examples don't work anymore. They need to be updated.

**Comment by nsoranzo** [comment]
Do you mean those in docs/examples/objects ? Which one in particular?

**Comment by gmauro** [comment]
Yes, and I collected here #358 some fixes

**Comment by nsoranzo** [comment]
@gmauro Can we close this?

**Comment by gmauro** [comment]
Yes, please.
Thank you
