### ISSUE TITLE
Add warnings for deprecated parameters and methods

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/bioblend#366]

**Comment by simonbray** [comment]
Can we maybe remove some completely, after they've been deprecated for a certain amount of time? For example, `get_current_history()` has a really misleading name and has been deprecated for over 5 years.

**Comment by nsoranzo** [comment]
Sure, I have been irregularly removing deprecated stuff in previous releases.

I've just removed `get_current_history()` and other long-deprecated methods in commit d7045945fff6139c95cc3677c8967e4110a602ac for 0.15.0 .
