### ISSUE TITLE
'GalaxyInstance' raises AttributeError when instantiated with email & password combination

### ISSUE THREAD

**Issue by pjbriggs** [galaxyproject/bioblend#398]
I've encountered an issue with creating a new instance of the `GalaxyInstance` class (in the `galaxy` module) with a user email and password combination. For example something like:

    from bioblend import galaxy
    gi = galaxy.GalaxyInstance(url="https://usegalaxy.org",key="foo")

works, but

    from bioblend import galaxy
    gi = galaxy.GalaxyInstance(url="https://usegalaxy.org",email="peter.briggs@manchester.ac.uk",password="bar")

raises an `AttributeError`:

    Traceback (most recent call last):
      File "bioblend_error.py", line 31, in <module>
        password="bar")
      File "XXXX/lib/python3.6/site-packages/bioblend/galaxy/__init__.py", line 75, in __init__
        super().__init__(url, key, email, password, verify=verify)
      File "XXXX/lib/python3.6/site-packages/bioblend/galaxyclient.py", line 68, in __init__
        'x-api-key': self.key,
      File "XXXX/lib/python3.6/site-packages/bioblend/galaxyclient.py", line 266, in key
        headers = self.json_headers.copy()
    AttributeError: 'GalaxyInstance' object has no attribute 'json_headers'

The issue is observed with Python 3.6.9 using `bioblend` 0.16.0 but is absent from version 0.15.0.

Any insight into addressing this issue would be welcome! Thanks
Peter

**Comment by simonbray** [comment]
Hi @pjbriggs, I pushed a fix here, can you test if it works for you? https://github.com/galaxyproject/bioblend/pull/399

**Comment by pjbriggs** [comment]
Hello @simonbray

The fix works for me (for both a simple example and within another application) so it looks good to me! 👍 

Thanks for looking at this so quickly!
