### ISSUE TITLE
Error running long workflow

### ISSUE THREAD

**Issue by hakattack** [galaxyproject/bioblend#41]
Hi,

I have ran long workflow (50 steps) and things seem to be working fine for sometimes before it crashes.  First all the data get loaded into the library.  The history gets created and then around 40/50 steps get scheduled (looking at the new created history).  The script keeps running but then it crashes and here is the log:

Traceback (most recent call last):
  File "run_imported_workflow.py", line 136, in <module>
    result = gi.workflows.run_workflow(workflow, datamap, history_id=outputhist, import_inputs_to_history=True)
  File "build/bdist.linux-x86_64/egg/bioblend/galaxy/workflows/__init__.py", line 177, in run_workflow
  File "build/bdist.linux-x86_64/egg/bioblend/galaxy/client.py", line 70, in _post
  File "build/bdist.linux-x86_64/egg/bioblend/galaxyclient.py", line 94, in make_post_request
bioblend.galaxy.client.ConnectionError: Unexpected response from galaxy: 500

My question, why only 40 not all the steps get scheduled?  Is the cause for the above issue relating to waiting time?  

By the way, the workflow gets executed if I just ran from the Galaxy GUI.

Any help is highly appreciated.

**Comment by nsoranzo** [comment]
Hi @hakattack,
`download_dataset()` method has been reworked in the mean time, is this still a problem for you?

If yes, can you please report it as another issue? This has been originally open for a different problem which seems to be fixed for you, so I'm closing this issue.
