### ISSUE TITLE
Incorrect PyYAML version for bioblend 0.9.0 - 0.16.0

### ISSUE THREAD

**Issue by hehao98** [galaxyproject/bioblend#412]
Hello,

PyYAML 6.0 recently introduce a breaking change in its `load()` function (yaml/pyyaml#576). BioBlend also uses the `load()` function in `bioblend/cloudman/launch.py` from version 0.9.0 - 1.16.0 while all versions do not specify an upper version bound for `pyyaml`. This means that users that recently install these BioBlend versions may also install the incompatible PyYAML 6.0 package.

Although the code has already been fixed, it has not been published in PyPI. Also, users using these old versions are still affected by this breaking change. Maybe it will be better to add an upper version bound for PyYAML in all these BioBlend releases?

**Comment by nsoranzo** [comment]
This was fixed in commit 2b85ca9f26d19bca6ab8f0b38a90262c4fdc55a7 , first released in [v0.17.0](https://github.com/galaxyproject/bioblend/releases/tag/v0.17.0).
