### ISSUE TITLE
Getting abosl

### ISSUE THREAD

**Issue by chambm** [galaxyproject/bioblend#413]
For `upload_from_galaxy_filesystem(preserve_dirs=False)`, do I understand correctly that the uploaded files should be placed in the indicated folder_id regardless of the filesystem paths that are being uploaded?

Because I'm not seeing that. I'm getting full absolute filepaths in 20.09 when using symlinks and `preserve_dirs=False` (which should be the default anyway.

**Comment by nsoranzo** [comment]
Sorry for the late reply! The uploaded files (or the symlinks) should be created in the indicated folder id, if I understand correctly what you are doing. If you are still experiencing this, could you provide an example call of `upload_from_galaxy_filesystem()`, what you get as result and what you would expect instead?
