### ISSUE TITLE
partial workflow invocation

### ISSUE THREAD

**Issue by lstrgar** [galaxyproject/bioblend#416]
I'm having trouble invoking and running the entirety of my workflow with bioblend. 

My pipeline is (1) input collection --> (2) BaSiC correction --> (3) Ashlar for stitching

(3) depends on (1) and (2) while (2) only depends on (1). 

Step (1) is working correctly but (3) never gets run. It's not even included in the history. 

Any suggestions for how to debug this? Or what the problem might be?

Thanks in advance.

**Comment by simonbray** [comment]
Can you provide some code please? (if it's possible to share the workflow, that would be helpful as well)

Are you able to run the workflow successfully in the UI?

Best wishes,

Simon

**Comment by lstrgar** [comment]
```
    gi = bioblend.galaxy.GalaxyInstance(url=config["galaxyUrl"], key=config["apikey"])
    ## workflow_args is a generator yielding tuples of history_id and hdca data description 
    workflow_args = upload_dir(config['datapath'], config['libraryId'], config['folderId'], config['workflow'], gi)
    wfdesc = get_workflow_description(gi, config['workflow'])
    workflow_id = wfdesc["uuid"]

    for hid, data in workflow_args:
        inputs = {
            '0': {
                "src": data['src'],
                "id": data['id'],
            },
        }
        res = gi.workflows.invoke_workflow(workflow_id, inputs, history_id=hid, import_inputs_to_history=False)
```

**Comment by lstrgar** [comment]
Does this link work for you?

https://galaxydev.ohsu.edu/u/strgar/w/crc-r01 

Invoking the workflow in the browser successfully completes the entire pipeline.

**Comment by simonbray** [comment]
I cannot access that link - I get `Server Not Found`.

If you can invoke it in the UI, I would suggest looking up the successful invocation id with `gi.invocations.show_invocations()` and checking that the `inputs` and `input_step_parameters` fields match what you are submitting via the API.

**Comment by lstrgar** [comment]
I had previously check input but I'll look at input_step_parameters.

If they differ how can I adjust the invocation to specify step parameters?

**Comment by simonbray** [comment]
You should be able to add `params=input_step_parameters` to `gi.workflows.invoke_workflow()`-

**Comment by lstrgar** [comment]
There are no differences in the input fields for jobs invoked from the command line and those invoked from the GUI.

**Comment by simonbray** [comment]
If you could share the workflow and some test data with me (either via a public Galaxy instance, or a chat like gitter or matrix, or in this issue, whatever you prefer) I can have a look. Not sure what else to suggest right now.

**Comment by lstrgar** [comment]
Sure gitter works. Thanks for your offer. Presumably your handle is gitter.im/simonbray?
