### ISSUE TITLE
Drop cloudlaunch support ?

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/bioblend#423]
@afgane @nuwang is it ok if we drop cloudman support and eliminate the boto dependency ? I think you decomissioned cloudlaunch, right ?

**Comment by mvdbeek** [comment]
(I mean https://github.com/galaxyproject/bioblend/tree/main/bioblend/cloudman, maybe I should have said cloudlaunch ?)

**Comment by nsoranzo** [comment]
@nuwang Is there anything in `bioblend/cloudman/` that is worth keeping? I can do the code removal once we are sure what to drop exactly.

**Comment by nuwang** [comment]
Not any longer, so the whole package can be dropped.
