### ISSUE TITLE
Workflow inputs are imported into history even when using 'import_inputs_to_history=False'

### ISSUE THREAD

**Issue by cjav** [galaxyproject/bioblend#44]
Hi,

I recently found this[1] issue. I believe this is more an issue on Galaxy, but after no response on galaxy-dev I was hoping reporting it here would help bring some attention to this issue affecting Bioblend.

Also and maybe related. I mentioned in the same email to galaxy-dev that in both cases, setting 'import_inputs_to_history' to 'False' or 'True', all inputs are imported to the history in duplicates.

[1]http://dev.list.galaxyproject.org/Issue-with-Bioblend-s-run-workflow-import-inputs-to-history-td4661726.html

Thanks,
Carlos

**Comment by nsoranzo** [comment]
Hi Carlos,
are you still experiencing this or can this issue be closed?

**Comment by cjav** [comment]
I haven't used bioblend or galaxy now for a while. It is possibly safe to close this issue. If I do find the time to test if the issue is still happening, I'll make sure to reopen this issue instead of opening a new one.

Thanks
