### ISSUE TITLE
Add support for parameter "all" in get_histories

### ISSUE THREAD

**Issue by Paprikant** [galaxyproject/bioblend#457]
The parameter can only be used by admins and is used to retrieve histories of all users (instead of just the user making the request)
It is documented [here](https://test.galaxyproject.org/api/docs#/histories/index_api_histories_get) and can be used as follows:

        # gi stores a GalaxyInstance using an admin key
        res = gi.make_get_request(gi.base_url + "/api/histories?q=name&qv=some-name&all=true")
        print(res.content)

However, having it as a parameter to `gi.histories.get_histories()` would be nice

**Comment by Paprikant** [comment]
I provided a PR that will maybe get this done. But I am not sure how to test this properly since i never worked with bioblend before

**Comment by nsoranzo** [comment]
Added in #458 .
