### ISSUE TITLE
Tool search in Toolshed: number total results 

### ISSUE THREAD

**Issue by gallardoalba** [galaxyproject/bioblend#462]
I'm trying to obtain the total number of hits when running:

`ts = toolshed.ToolShedInstance(url='https://toolshed.g2.bx.psu.edu')`
`search_hits = [hit['repository']['name'] for hit in ts.repositories.search_repositories(tool)['hits']]`

However, when I fetch the total number of results by using the following command:

`total_hits = ts.repositories.search_repositories(tool)["total_results"]`

The maximum value that I obtain is 280; it is problematic in some cases (e.g. with the **red** tool), because the correct hit is found only when 550 hits are requested (e.g. by using _ts.repositories.search_repositories(tool,page_size=550)_).

**Comment by nsoranzo** [comment]
@gallardoalba Thanks for opening the issue! BioBlend doesn't have control on the values returned in the search, so the "total_results" mismatch seems mainly a Galaxy bug.
What I can do is add support for the `name` and `owner` parameters to `ts.repositories.search_repositories()`, which should give you a perfect hit: https://toolshed.g2.bx.psu.edu/api/repositories?name=red&owner=iuc

**Comment by gallardoalba** [comment]
Sounds good, thanks a lot!

**Comment by nsoranzo** [comment]
@gallardoalba https://pypi.org/project/bioblend/1.0.0/

**Comment by gallardoalba** [comment]
> @gallardoalba https://pypi.org/project/bioblend/1.0.0/

Thanks!
