### ISSUE TITLE
Bioblend reporting workflow as failed while workflow is running or completed successfully. 

### ISSUE THREAD

**Issue by anilthanki** [galaxyproject/bioblend#474]
I am submitting a [workflow](https://github.com/anilthanki/galaxy-workflows/blob/main/SC/Galaxy-Workflow-Persist-Seq_v0.3.4.ga) to our private galaxy using [galaxy-workflow-executor](https://github.com/ebi-gene-expression-group/galaxy-workflow-executor), which uses BioBlend underneath.

When checking for invocation (`gi.workflows.show_invocation`) following submission after a while Bioblend reports state as fail while actual workflow is running or completed successfully.

**Comment by nsoranzo** [comment]
BioBlend is just a thin wrapper on top of the Galaxy API, so just passing back the invocation status from Galaxy.

You are probably passing the wrong invocation id, but would need to look at your code to confirm.

Any way, I'd recommend to use `gi.invocations.show_invocation()` instead.

**Comment by anilthanki** [comment]
I get same status with `gi.invocations.show_invocation()`

**Comment by nsoranzo** [comment]
You are probably passing the wrong invocation id, but would need to look at your code to confirm.

**Comment by anilthanki** [comment]
This is snippet of our code

```
results = gi.workflows.invoke_workflow(workflow_id=workflow_id,
                                                       inputs=datamap,
                                                       params=params,
                                                       history_name=(args.history + '_results'))
                                                       
invocation = gi.workflows.show_invocation(workflow_id=results['workflow_id'], invocation_id=results['id'])
```

**Comment by nsoranzo** [comment]
That looks correct. Any idea @mvdbeek ?

**Comment by mvdbeek** [comment]
The invocation probably is failed ... look at your invocation in Users -> Invocation.
