### ISSUE TITLE
docs for tool_inputs parameter to run_tool()

### ISSUE THREAD

**Issue by andreyto** [galaxyproject/bioblend#71]
I could not find anything anywhere on how to construct tool_inputs dictionary for `GalaxyInstance.tools.run_tool()` method. Could you document it, please?

It is not immediately obvious neither from your `tests/TestGalaxyTools.py` nor from Galaxy code in `lib/galaxy/webapps/galaxy/api/tools.py`.

I also notice that executing workflows, as opposed as tools, is much better documented both here and in Galaxy API Wiki. Is that by intent? Is running tools directly discouraged? The problem with workflows is that they have to be hand-edited every time the tools used in them are upgraded.

Thanks,
Andrey

**Comment by ecunha1996** [comment]
Hello,

I'm having some problems with the tool_inputs to run tools, especially setting the dataset.
Here is a simple example with fastq_info:

inputs = {"input_1": "bbd44e69cb8906b550b38de0ec289fcd", 'r': 'true'}
gi.tools.run_tool("b47d6ac96387d407" , gi.tools.show_tool("fastq_info")["id"], tool_inputs=inputs)

I checked the inputs with the show_tool method, and I'm able to change inputs whose argument is not None (like 'r', in the example above). However I cannot set the dataset, or other inputs whose argument is None.
How should I solve this?

Thanks in advance

**Comment by nsoranzo** [comment]
@ecunha1996 I guess that this should work for you:

```python
inputs = {"input_1": {src: "hda", id: "bbd44e69cb8906b550b38de0ec289fcd"}, "r": "true"}
```

**Comment by ecunha1996** [comment]
@nsoranzo I tried that but it keeps ignoring the dataset I select. I ran the tool directly in the galaxy portal, and than checked the inputs with the show_job method, and looked like this: 

 'inputs': {'fastq_1': {'id': 'bbd44e69cb8906b5b717152b0718556f',
                        'src': 'hda',
                        'uuid': 'aaf14c77-4631-4406-9b88-bb30bbe6770f'}}

Instead of using "input_1" I tried to use "fastq_1", but the problem remains.

**Comment by simonbray** [comment]
@ecunha1996 I think `show_tool()` is the wrong thing to check. The `state_inputs` returned by `build()` should be correct. That gives
```
{"input_option": {"input_type": "single", "fastq_1": {"values": [{"id": "bbd44e69cb8906b5b717152b0718556f", "src": "hda"}]}}, "q": "true", "r": "false"}
```
I hope that works for you? This should be better documented for sure. :/

**Comment by ecunha1996** [comment]
Using the state_inputs it works. 
Thanks a lot!

**Comment by simonbray** [comment]
I wrote a sentence in the docs directing users to the `build()` method: https://github.com/galaxyproject/bioblend/commit/984421d52d2d980143f756ea56338ceaf9cff8ce

Not sure if that is enough to close this issue?

**Comment by nsoranzo** [comment]
Yes, that's a good start, thanks @simonbray !
