### ISSUE TITLE
Use actual API endpoint for dataset downloads (at least for HDAs).

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/bioblend#84]
http://dev.list.galaxyproject.org/Problems-downloading-files-via-bioblend-td4665435.html

**Comment by erasche** [comment]
HA!

> Yes sorry about this - Eric reported this same problem this week. 

And I just re-discovered it and am bumping it again.

**Comment by erasche** [comment]
Testing a fix now....

**Comment by erasche** [comment]
#117
