### ISSUE TITLE
gi.workflows.list() fails when workflow contains unconnected input dataset 

### ISSUE THREAD

**Issue by bollig** [galaxyproject/bioblend#89]
I have a Galaxy workflow with a number of input datasets connected to a full graph of work. I also have two input datasets that are not connected to anything. So long as the two inputs exist without connection the Bioblend api throws an error: 

```Python
Traceback (most recent call last):
  File "/home/ubuntu/monitor.py", line 303, in <module>
    m.run_workflow(w_name, h_name, l_name)
  File "/home/ubuntu/monitor.py", line 283, in run_workflow
    raise e
AssertionError
```

Deleting the two inputs brings the API back to life.

**Comment by nsoranzo** [comment]
Closing, feel free to re-open if you can provide a stack trace.
