### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/bioblend#97]
Path forward:

- [x] Add dependency on [six](https://pypi.python.org/pypi/six).
- [ ] Switch all changed imports to use ``six.moves``, at this point all the files would be importable within Python 3 - which would help downstream projects like [planemo](https://github.com/jmchilton/planemo/commit/e41892bf321532f9ab1642761afaeb5db011c3e6).
- [x] Replace unmaintained `poster` dependency - ([requests-toolbelt](https://github.com/sigmavirus24/requests-toolbelt) may be a solution)
- [X] ~~Test dropping in [boto3](https://github.com/boto/boto3) in lieu of boto (or just wait for it to replace the project).~~ [Not needed](https://github.com/galaxyproject/bioblend/issues/97#issuecomment-86180237)
- [x] Update the actual BioBlend code for Python 3.
- [x] Use tox for testing.
- [ ] Setup a branch for Python 3 support using Travis to test against Python 3.4.

**Comment by nsoranzo** [comment]
See commits from 9036f902bad7278087033f3fe595ecdf2a3b818c to ef48b84e2cb26092869f27c23fa13ce997d1972d for an initial work on this.

**Comment by nsoranzo** [comment]
See pull request #131 .

**Comment by nsoranzo** [comment]
I think we don't need boto3, [boto documentation](http://docs.pythonboto.org/) says: "Work is under way to support Python 3.3+ in the same codebase. Modules are being ported one at a time with the help of the open source community."

Both EC2 and S3 are listed as already supported for Python 3.

**Comment by jmchilton** [comment]
Well that is fantastic! We just need to make poster an optional dependency or replace it - and then handle the dictionary iteration stuff. No promises, but I will try to find some time to take a crack at replacing poster tonight.

**Comment by nsoranzo** [comment]
I was trying to extend TravisCI testing to Python 3.4, but this tries to run also Galaxy with Python 3, which obviously does not work: https://travis-ci.org/nsoranzo/bioblend/jobs/55978112 . Ideas?

**Comment by jmchilton** [comment]
https://www.dominicrodger.com/tox-and-travis.html?

**Comment by nsoranzo** [comment]
So all the python interpreters are installed on the Travis nodes as ```pythonX.Y```, independently of the python version used for that particular build. Correct?

**Comment by nsoranzo** [comment]
> https://www.dominicrodger.com/tox-and-travis.html?

Thanks for the great suggestion @jmchilton ! Implemented in commit 8ecee207ff5901a555ae8c2f6b886392be964844.
